/**
 * miles-authorization
 * This service is used to get, set and verify feature rules, as well as self-registration templates.    For more information, check the **Read Me** tab.
 *
 * The version of the OpenAPI document: 1.20.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateSelfRegistrationTemplateRequest { 
    /**
     * The ID of the customer
     */
    customerId: string;
    /**
     * The ID of the contact category
     */
    contactCategoryId?: string;
    /**
     * The ID of the client
     */
    clientId?: string;
    /**
     *  A list of email domains for which complete self-registration is allowed, without a mobility manager who still needs to approve the new user
     */
    domains?: Set<string>;
}

