/**
 * miles-authorization
 * This service is used to get, set and verify feature rules, as well as self-registration templates.    For more information, check the **Read Me** tab.
 *
 * The version of the OpenAPI document: 1.20.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MultiLanguageValue } from './multi-language-value';
import { EnumValue } from './enum-value';


/**
 * Feature availability according to the provided query parameters
 */
export interface FeatureAvailability { 
    feature?: EnumValue;
    /**
     * Indicates whether the returned feature is available for the authorized user
     */
    isAvailable?: boolean;
    reason?: MultiLanguageValue;
}

