/**
 * miles-authorization
 * This service is used to get, set and verify feature rules, as well as self-registration templates.    For more information, check the **Read Me** tab.
 *
 * The version of the OpenAPI document: 1.20.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SimpleEnumValue } from './simple-enum-value';


/**
 * A feature rule to create and/or update
 */
export interface UpsertFeatureRule { 
    /**
     * The ID of the customer. Only one type of ID can be provided per call: customerId, contractCategoryId or contactId.
     */
    customerId?: string;
    /**
     * The ID of the contact category. Only one type of ID can be provided per call: customerId, contractCategoryId or contactId.
     */
    contactCategoryId?: string;
    /**
     * The ID of the contact. Only one type of ID can be provided per call: customerId, contractCategoryId or contactId.
     */
    contactId?: string;
    feature?: SimpleEnumValue;
    /**
     * Indicates whether the feature will always or never be available for the authorized user. Note that the daysBeforeExpectedContractEndDate and maxNumberApprovedQuotes parameters cannot be set in combination with this parameter.
     */
    isAvailable?: boolean;
    /**
     * The number of days before the expected end date of the contract, as of which the feature should be made available. Note that the isAvailable and maxNumberApprovedQuotes parameters cannot be set in combination with this parameter.
     */
    daysBeforeExpectedContractEndDate?: number;
    /**
     * The maximum number of quotes that can be approved before the feature should be made unavailable. Note that the isAvailable and daysBeforeExpectedContractEndDate parameters cannot be set in combination with this parameter.
     */
    maxNumberApprovedQuotes?: number;
}

