/**
 * miles-quotation
 * This service supports creation, calculation and follow-up of sales quotes (price proposals), typically    involving selection/configuration of a vehicle/asset and a choice of finance or rental product.
 *
 * The version of the OpenAPI document: 4.113.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SimpleEnumValue } from './simple-enum-value';


/**
 * The address
 */
export interface AddressRequest { 
    /**
     * ID of the address
     */
    addressId?: string;
    /**
     * Address line 1
     */
    addressLine1?: string;
    /**
     * Address line 1 number
     */
    addressLine1Number?: string;
    /**
     * Address line 2
     */
    addressLine2?: string;
    /**
     * Address line 3
     */
    addressLine3?: string;
    /**
     * Address line 4
     */
    addressLine4?: string;
    /**
     * Address line 5
     */
    addressLine5?: string;
    /**
     * The address formatted
     */
    formattedAddress?: string;
    /**
     * City
     */
    city?: string;
    /**
     * Postal code
     */
    postalCode?: string;
    /**
     * State
     */
    state?: string;
    /**
     * Location identification
     */
    locationIdentification?: string;
    /**
     * Indicates whether the address must be deleted. Note that deletion is only possible when the address ID is given.
     */
    isDeleted?: boolean;
    /**
     * Country
     */
    country?: string;
    addressType?: SimpleEnumValue;
}

