/**
 * miles-quotation
 * This service supports creation, calculation and follow-up of sales quotes (price proposals), typically    involving selection/configuration of a vehicle/asset and a choice of finance or rental product.
 *
 * The version of the OpenAPI document: 4.113.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EnumValue } from './enum-value';
import { AllowedService } from './allowed-service';


/**
 * The product configuration containing the allowed services for this quotation template
 */
export interface AllowedProductConfiguration { 
    /**
     * The reference of the product configuration
     */
    reference?: string;
    /**
     * Type ID of the product
     */
    productTypeId?: string;
    ProductCategory?: EnumValue;
    /**
     * A list of services
     */
    services?: Array<AllowedService>;
}

