/**
 * miles-quotation
 * This service supports creation, calculation and follow-up of sales quotes (price proposals), typically    involving selection/configuration of a vehicle/asset and a choice of finance or rental product.
 *
 * The version of the OpenAPI document: 4.113.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MultiLanguageValue } from './multi-language-value';
import { EnumValue } from './enum-value';


/**
 * A quotation template
 */
export interface AvailableQuotationTemplate { 
    /**
     * The ID of the quotation template
     */
    quotationTemplateId?: string;
    name?: MultiLanguageValue;
    quotationTemplateCategory?: EnumValue;
    /**
     * The date from which the quotation template is available, specified date included
     */
    availableFrom?: string;
    /**
     * The date until the quotation template is available, specified date excluded
     */
    availableTo?: string;
    quotationTemplateStatus?: EnumValue;
    quotationTemplateContractType?: EnumValue;
    /**
     * Additional information provided as a result of the evaluation of the rules
     */
    additionalFields?: { [key: string]: string; };
}

