/**
 * miles-quotation
 * This service supports creation, calculation and follow-up of sales quotes (price proposals), typically    involving selection/configuration of a vehicle/asset and a choice of finance or rental product.
 *
 * The version of the OpenAPI document: 4.113.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DynamicAttributeValue } from './dynamic-attribute-value';
import { MultiCurrencyValue } from './multi-currency-value';
import { VehicleDiscountConfiguration } from './vehicle-discount-configuration';
import { MultiLanguageValue } from './multi-language-value';
import { EnumValue } from './enum-value';
import { VehicleExtraDiscountConfiguration } from './vehicle-extra-discount-configuration';
import { Model } from './model';
import { VehicleConfiguration } from './vehicle-configuration';
import { Make } from './make';
import { Supplier } from './supplier';


/**
 * The bike, it can only return a bike or a car not both
 */
export interface Bike { 
    /**
     * The ID of the quote vehicle
     */
    quoteVehicleId?: string;
    description?: MultiLanguageValue;
    /**
     * The ID of the catalog bike
     */
    catalogBikeId?: string;
    /**
     * The make ID, deprecated since 2023-05-03 and version 4.81.0 in favor of make.id
     */
    makeId?: string;
    makeName?: MultiLanguageValue;
    modelName?: MultiLanguageValue;
    /**
     * Type of bike
     */
    typeName?: string;
    /**
     * The year of the model, deprecated since 2023-05-03 and version 4.81.0 in favor of model.year
     */
    modelYear?: string;
    frameType?: EnumValue;
    /**
     * The size of the frame
     */
    frameSize?: string;
    /**
     * The color of the bike
     */
    color?: string;
    /**
     * The type of the wheel
     */
    wheelType?: string;
    /**
     * Number of gears
     */
    gears?: string;
    /**
     * Whether the lock is standard
     */
    lockStandard?: boolean;
    lockPrice?: MultiCurrencyValue;
    lockPriceInclVat?: MultiCurrencyValue;
    lockDescription?: MultiLanguageValue;
    /**
     * Extra information
     */
    extraInfo?: string;
    nature?: EnumValue;
    catalogVatCode?: EnumValue;
    tax?: MultiCurrencyValue;
    netPrice?: MultiCurrencyValue;
    netPriceInclVat?: MultiCurrencyValue;
    catalogPrice?: MultiCurrencyValue;
    consumerPrice?: MultiCurrencyValue;
    /**
     * Discount percentage
     */
    discountPercentage?: number;
    discountAmount?: MultiCurrencyValue;
    discountAmountInclVat?: MultiCurrencyValue;
    /**
     * Whether its imposed by the dealer
     */
    isDealerImposed?: boolean;
    /**
     * The date on when the configuration is changed
     */
    configurationChangedDate?: string;
    /**
     * The date on when the validation has happened
     */
    validationDate?: string;
    totalOptionPrice?: MultiCurrencyValue;
    supplier?: Supplier;
    /**
     * A list of vehicle configurations
     */
    vehicleConfigurations?: Array<VehicleConfiguration>;
    /**
     * A list of vehicle extra discount configurations
     */
    vehicleExtraDiscountConfigurations?: Array<VehicleExtraDiscountConfiguration>;
    /**
     * A list of vehicle extra discount configurations
     */
    vehicleDiscountConfigurations?: Array<VehicleDiscountConfiguration>;
    /**
     * A map of dynamic attributes
     */
    dynamicAttributes?: { [key: string]: DynamicAttributeValue; };
    model?: Model;
    make?: Make;
}

