/**
 * miles-quotation
 * This service supports creation, calculation and follow-up of sales quotes (price proposals), typically    involving selection/configuration of a vehicle/asset and a choice of finance or rental product.
 *
 * The version of the OpenAPI document: 4.113.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MultiCurrencyValue } from './multi-currency-value';
import { ConfigOptionRequest } from './config-option-request';
import { ProductConfigurationUpdate } from './product-configuration-update';
import { QuotationTemplateUpdate } from './quotation-template-update';
import { UpfrontPaymentRequest } from './upfront-payment-request';
import { ConfigDiscountRequest } from './config-discount-request';
import { SimpleDynamicAttributeValue } from './simple-dynamic-attribute-value';
import { DeliveryCostComponentRequest } from './delivery-cost-component-request';


export interface CalculateSalesQuoteRequest { 
    productConfiguration?: ProductConfigurationUpdate;
    quotationTemplate?: QuotationTemplateUpdate;
    residualValue?: MultiCurrencyValue;
    residualValueAmount?: MultiCurrencyValue;
    /**
     * Residual value percentage; note that the residualValueAmount parameter cannot be set in combination with this parameter.
     */
    residualValuePercentage?: number;
    /**
     * Term of the leasing agreement
     */
    term?: number;
    /**
     * Maximum mileage of the leasing agreement
     */
    mileage?: number;
    /**
     * If the boolean is true, options will be the only that will be checked everything else will be ignored
     */
    onlyVerifyOptions?: boolean;
    /**
     * If the boolean is true, then the down payment will be cleared
     */
    resetDownPayment?: boolean;
    /**
     * Whether that the price is calculated with VAT or without VAT
     */
    isPriceInclusiveVat?: boolean;
    /**
     * Net price of the config vehicle with VAT. You need to provide exactly one net price, either the one with VAT (configVehicleNetPriceWithVat) or the one without VAT (configVehicleNetPriceWithoutVat)
     */
    configVehicleNetPriceWithVat?: number;
    /**
     * Net price of the config vehicle without VAT. You need to provide exactly one net price, either the one with VAT (configVehicleNetPriceWithVat) or the one without VAT (configVehicleNetPriceWithoutVat)
     */
    configVehicleNetPriceWithoutVat?: number;
    /**
     * Requested date when the delivery should happen
     */
    requestedDeliveryDate?: string;
    /**
     * The requested delivery location
     */
    reqestedDeliveryLocation?: string;
    /**
     * A list of config options
     */
    configOptions?: Array<ConfigOptionRequest>;
    /**
     * A list of discounts
     */
    configDiscounts?: Array<ConfigDiscountRequest>;
    /**
     * A list of delivery cost components
     */
    deliveryCostComponents?: Array<DeliveryCostComponentRequest>;
    /**
     * A map of dynamic attributes to update
     */
    dynamicAttributes?: { [key: string]: SimpleDynamicAttributeValue; };
    upfrontPayment?: UpfrontPaymentRequest;
}

