/**
 * miles-quotation
 * This service supports creation, calculation and follow-up of sales quotes (price proposals), typically    involving selection/configuration of a vehicle/asset and a choice of finance or rental product.
 *
 * The version of the OpenAPI document: 4.113.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MobilityPlanAllocationCalculation } from './mobility-plan-allocation-calculation';


export interface CalculateMobilityPlanAllocationRequest { 
    /**
     * ID of the mobility plan
     */
    mobilityPlanId: string;
    /**
     * ID of the driver
     */
    driverId?: string;
    /**
     * A list of mobility plan parts
     */
    mobilityPlanParts?: Array<MobilityPlanAllocationCalculation>;
}

