/**
 * miles-quotation
 * This service supports creation, calculation and follow-up of sales quotes (price proposals), typically    involving selection/configuration of a vehicle/asset and a choice of finance or rental product.
 *
 * The version of the OpenAPI document: 4.113.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DynamicAttributeValue } from './dynamic-attribute-value';
import { CreatedCustomer } from './created-customer';
import { EnumValue } from './enum-value';


export interface CoCustomerResponse { 
    /**
     * The ID of the co-customer
     */
    coCustomerId?: string;
    /**
     * The co-customer status
     */
    status?: number;
    /**
     * Last modified date
     */
    lastModified?: string;
    coCustomerType?: EnumValue;
    /**
     * The ID of the customer linked to the quote
     */
    customerId?: string;
    /**
     * The ID of the quote
     */
    salesQuoteId?: string;
    createdCustomer?: CreatedCustomer;
    /**
     * A map of dynamic attributes
     */
    dynamicAttributes?: Array<DynamicAttributeValue>;
}

