/**
 * miles-quotation
 * This service supports creation, calculation and follow-up of sales quotes (price proposals), typically    involving selection/configuration of a vehicle/asset and a choice of finance or rental product.
 *
 * The version of the OpenAPI document: 4.113.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SimpleDynamicAttributeValue } from './simple-dynamic-attribute-value';


export interface ConfirmSalesQuoteRequest { 
    /**
     * ID of the driver, you don\'t need to provide this property when you execute the endpoint confirmSalesQuote as a Driver/Broker/Dealer, otherwise this props is required
     */
    driverId?: string;
    /**
     * The ID of the site that should be attached to the quote. If not provided, the site that is attached to the quote will be removed.
     */
    siteId?: string;
    /**
     * Requested date when the delivery should happen
     */
    requestedDeliveryDate?: string;
    /**
     * ID of the dealer
     */
    dealerId?: string;
    /**
     * ID of the originating contract
     */
    originatingContractId?: string;
    /**
     * A map of dynamic attributes
     */
    dynamicAttributes?: { [key: string]: SimpleDynamicAttributeValue; };
}

