/**
 * miles-quotation
 * This service supports creation, calculation and follow-up of sales quotes (price proposals), typically    involving selection/configuration of a vehicle/asset and a choice of finance or rental product.
 *
 * The version of the OpenAPI document: 4.113.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MultiLanguageValue } from './multi-language-value';


/**
 * Contract that is using this mobility plan part
 */
export interface ContractBudgetAllocation { 
    /**
     * The contract ID
     */
    contractId?: string;
    /**
     * The reference of the contract
     */
    reference?: string;
    /**
     * The expected end date
     */
    expectedEndDate?: string;
    /**
     * The license plate of the car
     */
    licensePlate?: string;
    makeName?: MultiLanguageValue;
    modelName?: MultiLanguageValue;
}

