/**
 * miles-quotation
 * This service supports creation, calculation and follow-up of sales quotes (price proposals), typically    involving selection/configuration of a vehicle/asset and a choice of finance or rental product.
 *
 * The version of the OpenAPI document: 4.113.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ContactAddress } from './contact-address';
import { DynamicAttributeValue } from './dynamic-attribute-value';
import { PhoneNumber } from './phone-number';
import { IndividualPerson } from './individual-person';
import { InternetReference } from './internet-reference';


/**
 * The driver linked to the sales quote
 */
export interface CreateDriverLinkToSalesQuoteResponse { 
    /**
     * The ID of the driver
     */
    driverId?: string;
    person?: IndividualPerson;
    /**
     * A list of addresses
     */
    addresses?: Array<ContactAddress>;
    /**
     * A list of internet references
     */
    internetReferences?: Array<InternetReference>;
    /**
     * A list of phone numbers
     */
    phoneNumbers?: Array<PhoneNumber>;
    /**
     * A map of dynamic attributes
     */
    dynamicAttributes?: { [key: string]: DynamicAttributeValue; };
}

