/**
 * miles-quotation
 * This service supports creation, calculation and follow-up of sales quotes (price proposals), typically    involving selection/configuration of a vehicle/asset and a choice of finance or rental product.
 *
 * The version of the OpenAPI document: 4.113.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InternetReferenceRequest } from './internet-reference-request';
import { EnumValue } from './enum-value';
import { SimpleEnumValue } from './simple-enum-value';
import { IndividualPersonRequest } from './individual-person-request';
import { AddressRequest } from './address-request';
import { SimpleDynamicAttributeValue } from './simple-dynamic-attribute-value';
import { PhoneNumberRequest } from './phone-number-request';


/**
 * The customer to create and to be linked as a new co-customer to the sales quote
 */
export interface CreateCustomerToLinkAsCoCustomerToQuoteRequest { 
    /**
     * Company name. Property optional only for individual customers, required for non individual customers e.g. Organization
     */
    name?: string;
    individualPerson?: IndividualPersonRequest;
    legalEntity: SimpleEnumValue;
    /**
     * A list of addresses
     */
    addresses?: Array<AddressRequest>;
    /**
     * A list of internet references
     */
    internetReferences: Array<InternetReferenceRequest>;
    /**
     * A list of phone numbers
     */
    phoneNumbers?: Array<PhoneNumberRequest>;
    /**
     * Establishment date
     */
    establishmentDate?: string;
    /**
     * Official registration
     */
    officialRegistration?: string;
    /**
     * Additional customer reference. Typically used for mapping to other systems.
     */
    reference?: string;
    /**
     * Sector code
     */
    sectorCode?: string;
    taxLiability?: EnumValue;
    /**
     * VAT number
     */
    vatNumber?: string;
    /**
     * A map of dynamic attributes
     */
    dynamicAttributes?: { [key: string]: SimpleDynamicAttributeValue; };
}

