/**
 * miles-quotation
 * This service supports creation, calculation and follow-up of sales quotes (price proposals), typically    involving selection/configuration of a vehicle/asset and a choice of finance or rental product.
 *
 * The version of the OpenAPI document: 4.113.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateDocumentRequest { 
    /**
     * ID of the document template
     */
    documentTemplateId: string;
    /**
     * The ISO 639-1 or ISO 639-2 code of the language, in which the document will be generated. If not passed, the Miles back-office application will decide the language.
     */
    language?: string;
}

