/**
 * miles-quotation
 * This service supports creation, calculation and follow-up of sales quotes (price proposals), typically    involving selection/configuration of a vehicle/asset and a choice of finance or rental product.
 *
 * The version of the OpenAPI document: 4.113.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MultiCurrencyValue } from './multi-currency-value';


/**
 * Delivery cost component of configured delivery cost type
 */
export interface DeliveryCostComponent { 
    /**
     * ID of delivery cost components
     */
    id?: string;
    /**
     * Cost type ID of the delivery cost components
     */
    costTypeId?: string;
    costPrice?: MultiCurrencyValue;
    costVatAmount?: MultiCurrencyValue;
    costAmountInclVat?: MultiCurrencyValue;
    costDiscount?: MultiCurrencyValue;
    costAmount?: MultiCurrencyValue;
}

