/**
 * miles-quotation
 * This service supports creation, calculation and follow-up of sales quotes (price proposals), typically    involving selection/configuration of a vehicle/asset and a choice of finance or rental product.
 *
 * The version of the OpenAPI document: 4.113.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UnitValue } from './unit-value';


/**
 * Miles API v1 representation of a double with an additional unit value.
 */
export interface DoubleUnitValue { 
    /**
     * The value contains a decimal number
     */
    value?: number;
    unit?: UnitValue;
}

