/**
 * miles-quotation
 * This service supports creation, calculation and follow-up of sales quotes (price proposals), typically    involving selection/configuration of a vehicle/asset and a choice of finance or rental product.
 *
 * The version of the OpenAPI document: 4.113.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface EditSalesQuoteRequest { 
    /**
     * ID of the quotation template
     */
    quotationTemplateId?: string;
    /**
     * Term of the leasing agreement
     */
    term?: number;
    /**
     * Maximum mileage of the leasing agreement
     */
    mileage?: number;
    /**
     * If the boolean is true, then the down payment will be cleared
     */
    resetDownPayment?: boolean;
}

