/**
 * miles-quotation
 * This service supports creation, calculation and follow-up of sales quotes (price proposals), typically    involving selection/configuration of a vehicle/asset and a choice of finance or rental product.
 *
 * The version of the OpenAPI document: 4.113.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DynamicAttributeValue } from './dynamic-attribute-value';
import { DoubleUnitValue } from './double-unit-value';
import { Price } from './price';


/**
 * The quote product
 */
export interface FindQuoteProduct { 
    /**
     * The ID of the quote product
     */
    quoteProductId?: string;
    applicableLeasePrice?: Price;
    purchaseOptionValue?: Price;
    mileage?: DoubleUnitValue;
    annualMileage?: DoubleUnitValue;
    term?: DoubleUnitValue;
    /**
     * A map of dynamic attributes
     */
    dynamicAttributes?: { [key: string]: DynamicAttributeValue; };
}

