/**
 * miles-quotation
 * This service supports creation, calculation and follow-up of sales quotes (price proposals), typically    involving selection/configuration of a vehicle/asset and a choice of finance or rental product.
 *
 * The version of the OpenAPI document: 4.113.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Impact rule
 */
export interface ImpactRule { 
    /**
     * The impact rule ID
     */
    impactRuleId?: string;
    /**
     * The type enum ID
     */
    typeEnumID?: string;
    /**
     * The sys rep attribute ID
     */
    sysRepAttributeID?: string;
    /**
     * Whether it is incremental
     */
    incremental?: boolean;
    /**
     * Value of the impact
     */
    value?: string;
    /**
     * The catalog option type ID
     */
    catalogOptionTypeId?: string;
    /**
     * The discount type ID
     */
    discountTypeId?: string;
    /**
     * The cause
     */
    cause?: string;
}

