/**
 * miles-quotation
 * This service supports creation, calculation and follow-up of sales quotes (price proposals), typically    involving selection/configuration of a vehicle/asset and a choice of finance or rental product.
 *
 * The version of the OpenAPI document: 4.113.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SimpleEnumValue } from './simple-enum-value';


/**
 * Internet reference
 */
export interface InternetReferenceRequest { 
    /**
     * Internet reference url
     */
    url?: string;
    internetReferenceType?: SimpleEnumValue;
    /**
     * The internet reference ID
     */
    internetReferenceId?: string;
    /**
     * Indicates whether the internet reference needs to be deleted
     */
    isDeleted?: boolean;
}

