/**
 * miles-quotation
 * This service supports creation, calculation and follow-up of sales quotes (price proposals), typically    involving selection/configuration of a vehicle/asset and a choice of finance or rental product.
 *
 * The version of the OpenAPI document: 4.113.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MobilityPlanPartAllocation } from './mobility-plan-part-allocation';
import { EnumValue } from './enum-value';


/**
 * The mobility budget allocation
 */
export interface MobilityPlanAllocation { 
    /**
     * ID of the mobility plan
     */
    mobilityPlanId?: string;
    /**
     * The name of the mobility plan
     */
    name?: string;
    /**
     * Description for the mobility plan
     */
    description?: string;
    mobilityBudgetUnit?: EnumValue;
    leasePriceVisibility?: EnumValue;
    /**
     * A list of mobility plan part allocation
     */
    mobilityPlanParts?: Array<MobilityPlanPartAllocation>;
}

