/**
 * miles-quotation
 * This service supports creation, calculation and follow-up of sales quotes (price proposals), typically    involving selection/configuration of a vehicle/asset and a choice of finance or rental product.
 *
 * The version of the OpenAPI document: 4.113.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ImpactRule } from './impact-rule';


/**
 * Solution
 */
export interface OptionRuleSolution { 
    /**
     * Solution message
     */
    message?: string;
    /**
     * A list of IDs of the options you need to select for this solution
     */
    includeOptionIds?: Array<string>;
    /**
     * A list of IDs of the options you need to deselect for this solution
     */
    excludeOptionIds?: Array<string>;
    /**
     * A list of impact rules
     */
    impactRules?: Array<ImpactRule>;
    /**
     * A list of cause IDs
     */
    excludeVehicleOptionIds?: Array<string>;
}

