/**
 * miles-quotation
 * This service supports creation, calculation and follow-up of sales quotes (price proposals), typically    involving selection/configuration of a vehicle/asset and a choice of finance or rental product.
 *
 * The version of the OpenAPI document: 4.113.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OptionRuleSolution } from './option-rule-solution';


/**
 * Option rule violation
 */
export interface OptionRuleViolation { 
    /**
     * Whether the violation can be automatic solved
     */
    automatic?: boolean;
    /**
     * Message about the violation
     */
    message?: string;
    /**
     * A list of cause IDs
     */
    causeIds?: Array<string>;
    /**
     * A list of solutions
     */
    solutions?: Array<OptionRuleSolution>;
}

