/**
 * miles-quotation
 * This service supports creation, calculation and follow-up of sales quotes (price proposals), typically    involving selection/configuration of a vehicle/asset and a choice of finance or rental product.
 *
 * The version of the OpenAPI document: 4.113.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MultiLanguageValue } from './multi-language-value';


/**
 * Quote product price detail
 */
export interface ProductPricingDetailUpdate { 
    /**
     * The ID of the product pricing detail
     */
    id?: string;
    label?: MultiLanguageValue;
    /**
     * The edited value
     */
    editValue?: string;
}

