/**
 * miles-quotation
 * This service supports creation, calculation and follow-up of sales quotes (price proposals), typically    involving selection/configuration of a vehicle/asset and a choice of finance or rental product.
 *
 * The version of the OpenAPI document: 4.113.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MultiCurrencyValue } from './multi-currency-value';
import { MultiLanguageValue } from './multi-language-value';


/**
 * Product pricing detail
 */
export interface ProductPricingDetail { 
    /**
     * The ID of the product pricing detail
     */
    id?: string;
    label?: MultiLanguageValue;
    leasePrice?: MultiCurrencyValue;
    leaseVat?: MultiCurrencyValue;
    /**
     * The reference for the product pricing detail
     */
    reference?: string;
    /**
     * Whether the product pricing detail is editable
     */
    editable?: boolean;
    /**
     * The value that is edited
     */
    editValue?: string;
    /**
     * The category of the product pricing detail
     */
    category?: string;
    /**
     * Whether the product pricing detail is free text
     */
    isFreeText?: boolean;
    /**
     * Whether the product pricing detail is fixed
     */
    isFixed?: boolean;
}

