/**
 * miles-quotation
 * This service supports creation, calculation and follow-up of sales quotes (price proposals), typically    involving selection/configuration of a vehicle/asset and a choice of finance or rental product.
 *
 * The version of the OpenAPI document: 4.113.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MultiLanguageValue } from './multi-language-value';
import { AllowedProductConfiguration } from './allowed-product-configuration';


export interface QuotationTemplateAllowedServices { 
    /**
     * The ID of the quotation template
     */
    quotationTemplateId?: string;
    name?: MultiLanguageValue;
    productConfiguration?: AllowedProductConfiguration;
}

