/**
 * miles-quotation
 * This service supports creation, calculation and follow-up of sales quotes (price proposals), typically    involving selection/configuration of a vehicle/asset and a choice of finance or rental product.
 *
 * The version of the OpenAPI document: 4.113.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { QuotationTemplateMobilityPlanPart } from './quotation-template-mobility-plan-part';
import { EnumValue } from './enum-value';


/**
 * The mobility plan
 */
export interface QuotationTemplateMobilityPlan { 
    /**
     * ID of the mobility plan
     */
    mobilityPlanId?: string;
    /**
     * Name of the mobility plan
     */
    name?: string;
    /**
     * Description of the mobility plan
     */
    description?: string;
    mobilityBudgetUnit?: EnumValue;
    status?: EnumValue;
    /**
     * The default contact category ID
     */
    defaultContactCategoryId?: string;
    /**
     * A list of contact category ID\'s
     */
    otherContactCategoryIds?: Array<string>;
    /**
     * A list of quotation template mobility plan parts
     */
    mobilityPlanParts?: Array<QuotationTemplateMobilityPlanPart>;
}

