/**
 * miles-quotation
 * This service supports creation, calculation and follow-up of sales quotes (price proposals), typically    involving selection/configuration of a vehicle/asset and a choice of finance or rental product.
 *
 * The version of the OpenAPI document: 4.113.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The attribute on the sales quote that will be impacted by the recalculation to match the targeted lease price. Depending on your user roles, you can be allowed to use specific recalculation attributes or not.
 */
export type RecalculationAttribute = 'INVESTMENT' | 'INTEREST_RATE' | 'RESIDUAL_VALUE' | 'DEALER_DISCOUNT_AMOUNT' | 'CUSTOMER_UPFRONT' | 'DRIVER_UPFRONT';

export const RecalculationAttribute = {
    Investment: 'INVESTMENT' as RecalculationAttribute,
    InterestRate: 'INTEREST_RATE' as RecalculationAttribute,
    ResidualValue: 'RESIDUAL_VALUE' as RecalculationAttribute,
    DealerDiscountAmount: 'DEALER_DISCOUNT_AMOUNT' as RecalculationAttribute,
    CustomerUpfront: 'CUSTOMER_UPFRONT' as RecalculationAttribute,
    DriverUpfront: 'DRIVER_UPFRONT' as RecalculationAttribute
};

