/**
 * miles-quotation
 * This service supports creation, calculation and follow-up of sales quotes (price proposals), typically    involving selection/configuration of a vehicle/asset and a choice of finance or rental product.
 *
 * The version of the OpenAPI document: 4.113.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The recipients and reply-to of the email
 */
export interface Recipients { 
    /**
     * The list of email addresses to which a reply on the email needs to be sent
     */
    replyTo: Array<string>;
    /**
     * The list of recipient email addresses
     */
    to?: Array<string>;
    /**
     * The list of carbon copy recipient email addresses
     */
    cc?: Array<string>;
    /**
     * The list of blind carbon copy recipient email addresses
     */
    bcc?: Array<string>;
}

