/**
 * miles-quotation
 * This service supports creation, calculation and follow-up of sales quotes (price proposals), typically    involving selection/configuration of a vehicle/asset and a choice of finance or rental product.
 *
 * The version of the OpenAPI document: 4.113.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DoubleUnitValue } from './double-unit-value';
import { ProductDefaults } from './product-defaults';


export interface SalesQuoteDefaultsResponse { 
    /**
     * The investment of the quote
     */
    investment?: number;
    /**
     * The purchase option amount
     */
    purchaseOption?: number;
    /**
     * The customer upfront amount
     */
    upfrontAmount?: number;
    /**
     * Excess distance price
     */
    excessDistancePrice?: number;
    /**
     * Less distance price
     */
    underDistancePrice?: number;
    product?: ProductDefaults;
    mileage?: DoubleUnitValue;
    term?: DoubleUnitValue;
}

