/**
 * miles-quotation
 * This service supports creation, calculation and follow-up of sales quotes (price proposals), typically    involving selection/configuration of a vehicle/asset and a choice of finance or rental product.
 *
 * The version of the OpenAPI document: 4.113.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DynamicAttributeValue } from './dynamic-attribute-value';
import { Site } from './site';
import { QuotationTemplateReference } from './quotation-template-reference';
import { QuoteProduct } from './quote-product';
import { Customer } from './customer';
import { EnumValue } from './enum-value';
import { DriverReference } from './driver-reference';
import { SalesQuoteMobilityPlan } from './sales-quote-mobility-plan';
import { BrokerCompanyReference } from './broker-company-reference';
import { BrokerContact } from './broker-contact';
import { LeasingCompany } from './leasing-company';
import { Car } from './car';
import { SalesQuoteQuotationTemplate } from './sales-quote-quotation-template';
import { Bike } from './bike';


/**
 * The sales quote information
 */
export interface SalesQuote { 
    /**
     * The ID of the sales quote
     */
    salesQuoteId?: string;
    /**
     * The reference of the sales quote
     */
    reference?: string;
    /**
     * A description for the sales quote
     */
    description?: string;
    /**
     * The date on which the sales quote is created
     */
    creationDate?: string;
    /**
     * The date on which the sales quote will expire
     */
    expirationDate?: string;
    /**
     * The date on which the sales quote was last modified
     */
    lastModified?: string;
    /**
     * Whether the sales quote is approved
     */
    isApproved?: boolean;
    /**
     * The driver who requested the sales quote
     */
    requestDriverName?: string;
    /**
     * An external reference to the request
     */
    requestExternalReference?: string;
    /**
     * The user account ID who requested the sales quote
     */
    requestUserAccount?: string;
    /**
     * In non-fleet context this is the driver name that has been provided
     */
    providedDriverName?: string;
    /**
     * In non-fleet context this is the customer name that has been provided
     */
    providedCustomerName?: string;
    quoteReason?: EnumValue;
    quoteStatus?: EnumValue;
    quoteType?: EnumValue;
    requestType?: EnumValue;
    vehicleCategory?: EnumValue;
    vehicleNature?: EnumValue;
    customer?: Customer;
    brokerContact?: BrokerContact;
    /**
     * A list of broker companies
     */
    brokerCompanies?: Array<BrokerCompanyReference>;
    driverReference?: DriverReference;
    site?: Site;
    leasingCompany?: LeasingCompany;
    quoteProduct?: QuoteProduct;
    car?: Car;
    bike?: Bike;
    mobilityPlan?: SalesQuoteMobilityPlan;
    quotationTemplate?: QuotationTemplateReference;
    salesQuoteQuotationTemplate?: SalesQuoteQuotationTemplate;
    /**
     * Whether the discounts are hidden
     */
    discountsHidden?: boolean;
    /**
     * Whether the lease prices are hidden
     */
    leasePricesHidden?: boolean;
    /**
     * Whether the catalog prices are hidden
     */
    catalogPricesHidden?: boolean;
    /**
     * A map of dynamic attributes
     */
    dynamicAttributes?: { [key: string]: DynamicAttributeValue; };
}

