/**
 * miles-quotation
 * This service supports creation, calculation and follow-up of sales quotes (price proposals), typically    involving selection/configuration of a vehicle/asset and a choice of finance or rental product.
 *
 * The version of the OpenAPI document: 4.113.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DynamicAttributeValue } from './dynamic-attribute-value';
import { MultiCurrencyValue } from './multi-currency-value';
import { SalesQuotePricingDetailsDiscount } from './sales-quote-pricing-details-discount';
import { Price } from './price';
import { DeliveryCostComponent } from './delivery-cost-component';


export interface SalesQuotePricingDetails { 
    /**
     * The date on which the sales quote was last modified
     */
    lastModified?: string;
    applicableLeasePrice?: Price;
    leasePriceExclFuel?: MultiCurrencyValue;
    leasePriceExclFuelInclVat?: MultiCurrencyValue;
    leasePriceExclFuelEffectivePrice?: MultiCurrencyValue;
    leasePriceInclFuel?: MultiCurrencyValue;
    leasePriceInclFuelInclVat?: MultiCurrencyValue;
    leasePriceInclFuelEffectivePrice?: MultiCurrencyValue;
    leasePriceFuel?: MultiCurrencyValue;
    leasePriceVat?: MultiCurrencyValue;
    /**
     * Interest rate value
     */
    interestRateValue?: number;
    catalogVehiclePrice?: MultiCurrencyValue;
    catalogVehiclePriceVat?: MultiCurrencyValue;
    catalogVehiclePriceInclVat?: MultiCurrencyValue;
    catalogPrice?: MultiCurrencyValue;
    optionCatalogPriceVat?: MultiCurrencyValue;
    optionCatalogPriceInclVat?: MultiCurrencyValue;
    accessoriesCatalogPriceVat?: MultiCurrencyValue;
    accessoriesCatalogPriceInclVat?: MultiCurrencyValue;
    optionCatalogPrice?: MultiCurrencyValue;
    accessoriesCatalogPrice?: MultiCurrencyValue;
    totalPrice?: MultiCurrencyValue;
    totalPriceVat?: MultiCurrencyValue;
    totalPriceInclVat?: MultiCurrencyValue;
    totalVatAmount?: MultiCurrencyValue;
    catalogPriceVat?: MultiCurrencyValue;
    catalogPriceInclVat?: MultiCurrencyValue;
    fiscalValue?: MultiCurrencyValue;
    vehicleDiscountAmount?: MultiCurrencyValue;
    vehicleDiscountVatAmount?: MultiCurrencyValue;
    vehicleDiscountAmountInclVat?: MultiCurrencyValue;
    /**
     * ConfigDiscount percentage of type 100001 (Standard discount)
     */
    vehicleDiscountPercentage?: number;
    fleetDiscountAmount?: MultiCurrencyValue;
    /**
     * ConfigDiscount percentage of type 100002 (Fleet discount)
     */
    fleetDiscountPercentage?: number;
    dealerDiscountAmount?: MultiCurrencyValue;
    /**
     * ConfigDiscount percentage of type 100003 (Dealer discount)
     */
    dealerDiscountPercentage?: number;
    nonDealerDiscountAmount?: MultiCurrencyValue;
    /**
     * ConfigDiscount percentage of type 100004 (Non-dealer discount)
     */
    nonDealerDiscountPercentage?: number;
    optionDiscount?: MultiCurrencyValue;
    optionDiscountVatAmount?: MultiCurrencyValue;
    optionDiscountAmountInclVat?: MultiCurrencyValue;
    accessoryDiscount?: MultiCurrencyValue;
    accessoryDiscountVatAmount?: MultiCurrencyValue;
    accessoryDiscountAmountInclVat?: MultiCurrencyValue;
    extraWebDiscount?: MultiCurrencyValue;
    extraWebDiscountVatAmount?: MultiCurrencyValue;
    extraWebDiscountAmountInclVat?: MultiCurrencyValue;
    /**
     * A list of extra discounts
     */
    extraDiscounts?: Array<SalesQuotePricingDetailsDiscount>;
    commercialAction?: MultiCurrencyValue;
    /**
     * A list of delivery cost components of configured delivery cost model
     */
    deliveryCostComponents?: Array<DeliveryCostComponent>;
    totalFinancedDeliveryCost?: MultiCurrencyValue;
    totalDealerDeliveryCosts?: MultiCurrencyValue;
    totalDealerDeliveryCostsVat?: MultiCurrencyValue;
    totalDealerDeliveryCostsInclVat?: MultiCurrencyValue;
    totalOtherDeliveryCosts?: MultiCurrencyValue;
    totalOtherDeliveryCostsVat?: MultiCurrencyValue;
    totalOtherDeliveryCostsInclVat?: MultiCurrencyValue;
    totalDiscount?: MultiCurrencyValue;
    totalDiscounted?: MultiCurrencyValue;
    totalDiscountedVatAmount?: MultiCurrencyValue;
    totalDiscountedInclVat?: MultiCurrencyValue;
    tax?: MultiCurrencyValue;
    moreMileagePrice?: MultiCurrencyValue;
    lessMileagePrice?: MultiCurrencyValue;
    moreMileagePriceInclVat?: MultiCurrencyValue;
    lessMileagePriceInclVat?: MultiCurrencyValue;
    purchaseOptionValue?: Price;
    purchaseOptionValueVatAmount?: MultiCurrencyValue;
    purchaseOptionValueInclVat?: MultiCurrencyValue;
    /**
     * The ID of the quotation template
     */
    quotationTemplateId?: string;
    /**
     * A map of dynamic attributes
     */
    dynamicAttributes?: { [key: string]: DynamicAttributeValue; };
}

