/**
 * miles-quotation
 * This service supports creation, calculation and follow-up of sales quotes (price proposals), typically    involving selection/configuration of a vehicle/asset and a choice of finance or rental product.
 *
 * The version of the OpenAPI document: 4.113.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GeneratableDocument } from './generatable-document';
import { Recipients } from './recipients';


export interface SendMailSalesQuoteRequest { 
    /**
     * The ID of the document that needs to be attached to the email. Note that the generatableDocument parameter cannot be set in combination with this parameter.
     */
    documentId?: string;
    generatableDocument?: GeneratableDocument;
    /**
     * The subject of the email
     */
    subject?: string;
    /**
     * The body of the email
     */
    body?: string;
    /**
     * If the quote status needs to be updated if the sending of the email was successful
     */
    updateQuoteStatusOnSuccess?: boolean;
    recipients: Recipients;
}

