/**
 * miles-quotation
 * This service supports creation, calculation and follow-up of sales quotes (price proposals), typically    involving selection/configuration of a vehicle/asset and a choice of finance or rental product.
 *
 * The version of the OpenAPI document: 4.113.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { QualifierSettingUpdate } from './qualifier-setting-update';
import { ServiceChoiceUpdate } from './service-choice-update';


/**
 * Service
 */
export interface ServiceUpdate { 
    /**
     * Reference of service
     */
    reference?: string;
    /**
     * A list of services choices
     */
    choices?: Array<ServiceChoiceUpdate>;
    /**
     * A list of qualifier settings
     */
    qualifierSettings?: Array<QualifierSettingUpdate>;
}

