/**
 * miles-quotation
 * This service supports creation, calculation and follow-up of sales quotes (price proposals), typically    involving selection/configuration of a vehicle/asset and a choice of finance or rental product.
 *
 * The version of the OpenAPI document: 4.113.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MultiCurrencyValue } from './multi-currency-value';
import { MultiLanguageValue } from './multi-language-value';


/**
 * Service choice
 */
export interface ServiceChoice { 
    /**
     * The ID of the service choice
     */
    id?: string;
    label?: MultiLanguageValue;
    /**
     * Whether the service choice is selected
     */
    isSelected?: boolean;
    leasePrice?: MultiCurrencyValue;
    leaseVat?: MultiCurrencyValue;
}

