/**
 * miles-quotation
 * This service supports creation, calculation and follow-up of sales quotes (price proposals), typically    involving selection/configuration of a vehicle/asset and a choice of finance or rental product.
 *
 * The version of the OpenAPI document: 4.113.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MultiCurrencyValue } from './multi-currency-value';
import { MultiLanguageValue } from './multi-language-value';
import { EnumValue } from './enum-value';
import { QualifierValue } from './qualifier-value';


/**
 * Vehicle Configuration
 */
export interface VehicleConfiguration { 
    /**
     * The vehicle configuration ID
     */
    vehicleConfigurationId?: string;
    catalogPrice?: MultiCurrencyValue;
    consumerPrice?: MultiCurrencyValue;
    tax?: MultiCurrencyValue;
    description?: MultiLanguageValue;
    /**
     * Whether the option is standard
     */
    isStandard?: boolean;
    /**
     * Whether the option is selected
     */
    isSelected?: boolean;
    /**
     * Whether the option is mandatory
     */
    isMandatory?: boolean;
    /**
     * Whether the option is mandatory accessory
     */
    isMandatoryAccessory?: boolean;
    /**
     * The option code
     */
    optionCode?: string;
    qualifier1?: QualifierValue;
    qualifier2?: QualifierValue;
    qualifier3?: QualifierValue;
    catalogVatCode?: EnumValue;
    optionType?: EnumValue;
    /**
     * The ID of the supplier
     */
    supplierId?: string;
    /**
     * The catalog option type ID
     */
    catalogOptionTypeId?: string;
    /**
     * The generic option ID
     */
    genericOptionId?: string;
    annotations?: MultiLanguageValue;
    /**
     * A list of vehicle configurations packs
     */
    vehicleConfigurationPacks?: Array<VehicleConfiguration>;
    /**
     * A list of vehicle configurations
     */
    vehicleConfigurations?: Array<VehicleConfiguration>;
}

