/**
 * miles-quotation
 * This service supports creation, calculation and follow-up of sales quotes (price proposals), typically    involving selection/configuration of a vehicle/asset and a choice of finance or rental product.
 *
 * The version of the OpenAPI document: 4.113.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MultiCurrencyValue } from './multi-currency-value';
import { SimpleEnumValue } from './simple-enum-value';
import { SimpleDynamicAttributeValue } from './simple-dynamic-attribute-value';


/**
 * The config vehicle data to be updated prior calculation
 */
export interface VehicleRequest { 
    /**
     * The date on which the vehicle was registered for the first time
     */
    firstRegistrationDate?: string;
    /**
     * The vehicle net price
     */
    vehiclePriceNet?: number;
    catalogPrice?: MultiCurrencyValue;
    /**
     * The distance the vehicle has already been driven up to now
     */
    mileage?: number;
    /**
     * The chassis number of the vehicle
     */
    chassisNumber?: string;
    registrationCode?: SimpleEnumValue;
    /**
     * The total weight of the vehicle
     */
    totalWeight?: number;
    /**
     * The number of kilowatts of the engine of the vehicle
     */
    kw?: number;
    /**
     * The vehicle consumption
     */
    consumption?: number;
    /**
     * The vehicle CO2 emission
     */
    co2Emission?: number;
    /**
     * Vehicle description
     */
    vehicleDescription?: string;
    nature?: SimpleEnumValue;
    /**
     * The requested delivery date
     */
    requestedDeliveryDate?: string;
    /**
     * License plate
     */
    licensePlate?: string;
    /**
     * A map of dynamic attributes
     */
    dynamicAttributes?: { [key: string]: SimpleDynamicAttributeValue; };
}

