/**
 * miles-user-management
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.12.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * List of groups where the user is part of
 */
export interface FindUserGroup { 
    /**
     * User Group Id
     */
    userGroupId?: string;
}

