/**
 * miles-user-management
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.12.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MultiLanguageValue } from './multi-language-value';


/**
 * A list of user groups
 */
export interface UserGroup { 
    /**
     * User Group Id
     */
    userGroupId?: string;
    description?: MultiLanguageValue;
}

