/**
 * miles-car-quote
 * This service is used to create and copy car quotes.
 *
 * The version of the OpenAPI document: 1.74.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SimpleEnumValue } from './simple-enum-value';


/**
 * Addresses
 */
export interface AddressRequest { 
    /**
     * The address ID
     */
    addressId?: string;
    /**
     * Indicates whether the address needs to be deleted
     */
    isDeleted?: boolean;
    /**
     * Address line 1
     */
    addressLine1?: string;
    /**
     * Address line 1 number
     */
    addressLine1Number?: string;
    /**
     * Address line 2
     */
    addressLine2?: string;
    /**
     * Address line 3
     */
    addressLine3?: string;
    /**
     * Address line 4
     */
    addressLine4?: string;
    /**
     * Address line 5
     */
    addressLine5?: string;
    /**
     * City
     */
    city?: string;
    /**
     * Postal code
     */
    postalCode?: string;
    /**
     * State
     */
    state?: string;
    /**
     * Country code
     */
    country?: string;
    addressType?: SimpleEnumValue;
}

