/**
 * miles-car-quote
 * This service is used to create and copy car quotes.
 *
 * The version of the OpenAPI document: 1.74.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The calculate sales quote info
 */
export interface CalculateQuoteInfo { 
    /**
     * Difference between the budget and the lease price
     */
    budgetDifference?: number;
    /**
     * The budget
     */
    budget?: number;
    /**
     * Whether the lease price reached the maximum of the budget
     */
    warningBudgetReachingMaximum?: boolean;
    /**
     * Whether there are violations of the fleet policy
     */
    fleetPolicyViolated?: boolean;
    /**
     * Whether a down payment is allowed or not
     */
    downPaymentAllowed?: boolean;
    /**
     * Whether accessories are allowed or not
     */
    accessoriesNotAllowed?: boolean;
    /**
     * Whether it is possible to change who will pay the down payment
     */
    invoicingTargetEditable?: boolean;
    /**
     * Who will pay the invoice of the down payment
     */
    invoicingTargetDefault?: string;
    /**
     * Whether the price is visible
     */
    pricesVisible?: boolean;
    /**
     * Whether a budget is set
     */
    budgetIsSet?: boolean;
    /**
     * The remaining optional equipment budget
     */
    remainingOptionalEquipmentBudget?: number;
    /**
     * Whether the remaining optional equipment budget has exceeded
     */
    remainingOptionalEquipmentBudgetExceeded?: boolean;
    /**
     * The optional equipment budget set on the car policy
     */
    optionalEquipmentBudget?: number;
    /**
     * The upgrade cost defined in the car policy for that car
     */
    upgradeCost?: number;
    /**
     * The downgrade compensation defined in the car policy for that car
     */
    downgradeCompensation?: number;
    /**
     * The maximum amount of upfront you can use
     */
    maximumUpfrontPayment?: number;
    /**
     * This value will be filled as informational if you have configured upgrade cost impact to \'Internal company arrangement\' on the car policy 
     */
    informationalUpfrontPayment?: number;
    /**
     * Whether the upfront limit has exceeded
     */
    isUpfrontLimitExceeded?: boolean;
}

