/**
 * miles-car-quote
 * This service is used to create and copy car quotes.
 *
 * The version of the OpenAPI document: 1.74.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OptionRuleViolation } from './option-rule-violation';
import { ImpactRule } from './impact-rule';


/**
 * The config option violations that should be fixed before the quote could be succesfully validated.
 */
export interface ConfigOptionViolation { 
    violations?: Array<OptionRuleViolation>;
    impactRules?: Array<ImpactRule>;
}

