/**
 * miles-car-quote
 * This service is used to create and copy car quotes.
 *
 * The version of the OpenAPI document: 1.74.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CustomerRequest } from './customer-request';
import { SimpleEnumValue } from './simple-enum-value';
import { UsedVehicleInformationRequest } from './used-vehicle-information-request';


export interface CreateUsedCarQuoteRequest { 
    /**
     * The ID of the customer
     */
    customerId?: string;
    legalEntityGroup?: SimpleEnumValue;
    /**
     * The ID of the catalog vehicle. One of the `catalogVehicleId` or `catalogVehicleReference` parameters is required, but both cannot be set together.
     */
    catalogVehicleId?: string;
    /**
     * The reference of the catalog vehicle. One of the `catalogVehicleId` or `catalogVehicleReference` parameters is required, but both cannot be set together.
     */
    catalogVehicleReference?: string;
    /**
     * The ID of the quotation template
     */
    quotationTemplateId?: string;
    /**
     * The term on the car quote of the leasing agreement
     */
    term?: number;
    /**
     * The maximum mileage of the car quote of the leasing agreement
     */
    mileage?: number;
    customer?: CustomerRequest;
    usedVehicle: UsedVehicleInformationRequest;
}

