/**
 * miles-car-quote
 * This service is used to create and copy car quotes.
 *
 * The version of the OpenAPI document: 1.74.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Vehicle } from './vehicle';
import { CustomerRequest } from './customer-request';
import { EnumValue } from './enum-value';
import { SimpleEnumValue } from './simple-enum-value';
import { AllocatedDriver } from './allocated-driver';


export interface CreateCarQuoteRequest { 
    /**
     * The ID of the customer
     */
    customerId?: string;
    legalEntityGroup?: SimpleEnumValue;
    /**
     * The ID of the catalog vehicle. One of the `catalogVehicleId` or `catalogVehicleReference` parameters is required, but both cannot be set together.
     */
    catalogVehicleId?: string;
    /**
     * The reference of the catalog vehicle. One of the `catalogVehicleId` or `catalogVehicleReference` parameters is required, but both cannot be set together.
     */
    catalogVehicleReference?: string;
    /**
     * The ID of the quotation template
     */
    quotationTemplateId?: string;
    /**
     * The term on the car quote of the leasing agreement
     */
    term?: number;
    /**
     * The maximum mileage of the car quote of the leasing agreement
     */
    mileage?: number;
    customer?: CustomerRequest;
    /**
     * The car policy vehicle ID
     */
    carPolicyVehicleId?: string;
    /**
     * The driver contact ID
     */
    driverContactId?: string;
    /**
     * The duration on the product
     */
    duration?: number;
    /**
     * The distance on the product
     */
    distance?: number;
    quoteReason?: EnumValue;
    /**
     * Flag indicating if a dummy quotation template is used
     */
    dummyQuotationTemplate?: boolean;
    /**
     * Flag indicating if we need to run a quote calculation or not, this flag can be ignored when you are using a list based car policy
     */
    calculateQuote?: boolean;
    vehicle?: Vehicle;
    allocatedDriver?: AllocatedDriver;
    /**
     * Indicates whether the budget strategy \'Price Indication\' must be taken into account to indicate if the lease price and lease VAT should be included for all choices that have not been selected (isSelected = false).
     */
    includePriceIndication?: boolean;
}

