/**
 * miles-car-quote
 * This service is used to create and copy car quotes.
 *
 * The version of the OpenAPI document: 1.74.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SimpleEnumValue } from './simple-enum-value';


/**
 * Vehicle free form accessories
 */
export interface FreeFormAccessories { 
    /**
     * The code of the catalog option. This is an additional code for the catalog option which will be used for interfacing purposes.
     */
    optionCode?: string;
    /**
     * The description of the generic option
     */
    description?: string;
    optionType?: SimpleEnumValue;
    /**
     * The catalog price of the configuration option.
     */
    catalogPrice?: number;
    /**
     * ID of the generic option
     */
    genericOptionId?: string;
}

