/**
 * miles-car-quote
 * This service is used to create and copy car quotes.
 *
 * The version of the OpenAPI document: 1.74.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SimpleEnumValue } from './simple-enum-value';


/**
 * Internet reference
 */
export interface InternetReferenceRequest { 
    /**
     * The internet reference ID
     */
    internetReferenceId?: string;
    /**
     * The URL of the reference
     */
    url?: string;
    internetReferenceType?: SimpleEnumValue;
    /**
     * Indicates whether the internet reference needs to be deleted
     */
    isDeleted?: boolean;
}

