/**
 * miles-car-quote
 * This service is used to create and copy car quotes.
 *
 * The version of the OpenAPI document: 1.74.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MultiLanguageValue } from './multi-language-value';


/**
 * The model of the car
 */
export interface Model { 
    /**
     * The ID of the model of the car
     */
    modelId?: string;
    modelName?: MultiLanguageValue;
    /**
     * The year of the model of the car
     */
    modelYear?: string;
}

