/**
 * miles-car-quote
 * This service is used to create and copy car quotes.
 *
 * The version of the OpenAPI document: 1.74.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Miles API v1 representation of a currency value.
 */
export interface MultiCurrencyValue { 
    /**
     * The value that holds the currency amount
     */
    value?: number;
    /**
     * The currency amount in a different currency
     */
    currencyValue?: number;
    /**
     * The ID of the currency
     */
    currencyId?: string;
}

