/**
 * miles-car-quote
 * This service is used to create and copy car quotes.
 *
 * The version of the OpenAPI document: 1.74.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProductSetting } from './product-setting';
import { ProductPricingDetail } from './product-pricing-detail';


/**
 * Product configuration
 */
export interface ProductConfiguration { 
    /**
     * The reference of the product configuration
     */
    reference?: string;
    /**
     * Type ID of the product
     */
    productTypeId?: string;
    /**
     * Indicates whether a price indication of the lease price and lease VAT should be included for all choices that have not been selected (isSelected = false)
     */
    includePriceIndication?: boolean;
    /**
     * A list of product settings, deprecated since 2020-08-31 and version \'1.25.0\' in favor of \'productSettings\'
     */
    prodSettings?: Array<ProductSetting>;
    /**
     * A list of product settings
     */
    productSettings?: Array<ProductSetting>;
    /**
     * A list of product pricing details
     */
    priceDetails?: Array<ProductPricingDetail>;
}

