/**
 * miles-car-quote
 * This service is used to create and copy car quotes.
 *
 * The version of the OpenAPI document: 1.74.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DynamicAttributeValue } from './dynamic-attribute-value';
import { MultiCurrencyValue } from './multi-currency-value';
import { DoubleUnitValue } from './double-unit-value';
import { ProductConfiguration } from './product-configuration';
import { MultiLanguageValue } from './multi-language-value';
import { Price } from './price';
import { EnumValue } from './enum-value';


/**
 * Use quoteProduct instead
 */
export interface Product { 
    /**
     * Product ID
     */
    productId?: string;
    description?: MultiLanguageValue;
    duration?: DoubleUnitValue;
    distance?: DoubleUnitValue;
    proRataDistance?: DoubleUnitValue;
    investment?: MultiCurrencyValue;
    applicableLeasePrice?: Price;
    otherLeasePrices?: { [key: string]: Price; };
    dynamicAttributes?: { [key: string]: DynamicAttributeValue; };
    customerUpfront?: MultiCurrencyValue;
    driverUpfront?: MultiCurrencyValue;
    residualValue?: MultiCurrencyValue;
    /**
     * Residual value percentage. Only returned for configured products, by default: \'Loan products\' and \'Lease Purchase
     */
    residualValuePercentage?: number;
    productConfiguration?: ProductConfiguration;
    productCategory?: EnumValue;
}

