/**
 * miles-car-quote
 * This service is used to create and copy car quotes.
 *
 * The version of the OpenAPI document: 1.74.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { QualifierSettingChoice } from './qualifier-setting-choice';


export interface QualifierSetting { 
    /**
     * The reference of the qualifier setting
     */
    reference?: string;
    /**
     * The list of conditions when the qualifier setting can be used
     */
    condition?: Array<string>;
    /**
     * The value of the qualifier setting
     */
    value?: string;
    /**
     * The datatype of the qualifier setting
     */
    dataType?: string;
    /**
     * The default value of the qualifier setting
     */
    defaultValue?: string;
    /**
     * The minimum value of the qualifier setting
     */
    minValue?: number;
    /**
     * The maximum value of the qualifier setting
     */
    maxValue?: number;
    /**
     * If the qualifier setting is required or not
     */
    required?: boolean;
    choices?: Array<QualifierSettingChoice>;
}

