/**
 * miles-car-quote
 * This service is used to create and copy car quotes.
 *
 * The version of the OpenAPI document: 1.74.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DynamicAttributeValue } from './dynamic-attribute-value';
import { MultiCurrencyValue } from './multi-currency-value';
import { DoubleUnitValue } from './double-unit-value';
import { ProductConfiguration } from './product-configuration';
import { MultiLanguageValue } from './multi-language-value';
import { Price } from './price';
import { EnumValue } from './enum-value';


/**
 * The quote product
 */
export interface QuoteProduct { 
    /**
     * The ID of the quote product
     */
    quoteProductId?: string;
    description?: MultiLanguageValue;
    term?: DoubleUnitValue;
    mileage?: DoubleUnitValue;
    annualMileage?: DoubleUnitValue;
    investment?: MultiCurrencyValue;
    applicableLeasePrice?: Price;
    /**
     * A map of other lease prices, the key is the enum ID of the budgetUnit and the value is a price object
     */
    otherLeasePrices?: { [key: string]: Price; };
    customerUpfront?: MultiCurrencyValue;
    driverUpfront?: MultiCurrencyValue;
    productConfiguration?: ProductConfiguration;
    productCategory?: EnumValue;
    residualValue?: MultiCurrencyValue;
    residualValueAmount?: MultiCurrencyValue;
    /**
     * Residual value percentage; It will be returned only for configured products, by default: \'Loan products\' and \'Lease Purchase\'
     */
    residualValuePercentage?: number;
    /**
     * The interest rate of the sales quote; It will be returned only for configured products, by default: \'Lease Purchase\' and \'Consumer Loan\'
     */
    interestRate?: number;
    /**
     * A map of dynamic attributes
     */
    dynamicAttributes?: { [key: string]: DynamicAttributeValue; };
    proRataDistance?: DoubleUnitValue;
}

