/**
 * miles-car-quote
 * This service is used to create and copy car quotes.
 *
 * The version of the OpenAPI document: 1.74.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProductComponent } from './product-component';
import { Rule } from './rule';


/**
 * The violations that should be fixed before the quote could be succesfully validated.
 */
export interface QuoteViolation { 
    missingRequiredProductComponents?: Array<ProductComponent>;
    multipleInstantiatedProductComponents?: Array<ProductComponent>;
    quotationTemplateErrorRules?: Array<Rule>;
    quotationTemplateWarningRules?: Array<Rule>;
    serviceFilterErrorRules?: Array<Rule>;
    serviceFilterWarningRules?: Array<Rule>;
}

