/**
 * miles-car-quote
 * This service is used to create and copy car quotes.
 *
 * The version of the OpenAPI document: 1.74.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The sales price of the used vehicle
 */
export interface SalesPriceRequest { 
    /**
     * The sales prices of the used vehicle with VAT. You need to provide exactly one sales price, either the one with VAT (salesPriceWithVat) or the one without VAT (salesPriceWithoutVat)
     */
    salesPriceWithVat?: number;
    /**
     * The sales prices of the used vehicle without VAT. You need to provide exactly one sales price, either the one with VAT (salesPriceWithVat) or the one without VAT (salesPriceWithoutVat)
     */
    salesPriceWithoutVat?: number;
}

