/**
 * miles-car-quote
 * This service is used to create and copy car quotes.
 *
 * The version of the OpenAPI document: 1.74.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The stock vehicle information
 */
export interface StockVehicleInformationResponse { 
    /**
     * The chassis number of the stock vehicle
     */
    chassisNumber?: string;
    /**
     * The date when this stock vehicle was configured
     */
    configurationDate?: string;
}

