/**
 * miles-car-quote
 * This service is used to create and copy car quotes.
 *
 * The version of the OpenAPI document: 1.74.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SimpleEnumValue } from './simple-enum-value';


/**
 * Information about the stock vehicle to make a sales quote for
 */
export interface StockVehicleInformationRequest { 
    /**
     * The chassis number of the stock vehicle
     */
    chassisNumber?: string;
    /**
     * The date on which this stock vehicle was configured. The current date is used by default.
     */
    configurationDate?: string;
    nature?: SimpleEnumValue;
}

