/**
 * miles-customer
 * This service is used to retrieve information about customers, fleet managers,    drivers & legal entity groups.    It can manage all things related to UBO and its documents.    Customers can be created, updated and links to them can be removed.    The service provides filters needed to manage all these objects.
 *
 * The version of the OpenAPI document: 1.128.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DynamicAttributeValue } from './dynamic-attribute-value';
import { EnumValue } from './enum-value';
import { Country } from './country';


/**
 * The person linked to the contact
 */
export interface ContactPersonResponse { 
    /**
     * First name
     */
    firstName?: string;
    /**
     * Last name
     */
    lastName?: string;
    /**
     * Second last name
     */
    secondLastName?: string;
    /**
     * The place of birth
     */
    placeOfBirth?: string;
    /**
     * Date of birth
     */
    dateOfBirth?: string;
    personTitle?: EnumValue;
    gender?: EnumValue;
    country?: Country;
    /**
     * The official registration of the person
     */
    officialRegistration?: string;
    /**
     * A map of dynamic attributes
     */
    dynamicAttributes?: { [key: string]: DynamicAttributeValue; };
}

