/**
 * miles-customer
 * This service is used to retrieve information about customers, fleet managers,    drivers & legal entity groups.    It can manage all things related to UBO and its documents.    Customers can be created, updated and links to them can be removed.    The service provides filters needed to manage all these objects.
 *
 * The version of the OpenAPI document: 1.128.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ContactAddress } from './contact-address';
import { DynamicAttributeValue } from './dynamic-attribute-value';
import { ContactPersonResponse } from './contact-person-response';
import { PhoneNumber } from './phone-number';
import { InternetReference } from './internet-reference';


export interface ContactResponse { 
    /**
     * The ID of the contact
     */
    contactId?: string;
    /**
     * The date on which the contact started at the customer
     */
    joinDate?: string;
    /**
     * The date on which the contact left the customer
     */
    leaveDate?: string;
    /**
     * Identification of the contact
     */
    identification?: string;
    /**
     * Job title of the contact
     */
    jobTitle?: string;
    /**
     * Employee number of the contact
     */
    employeeNumber?: string;
    /**
     * Additional comments for the contact
     */
    comments?: string;
    person?: ContactPersonResponse;
    /**
     * A list of phone numbers
     */
    phoneNumbers?: Array<PhoneNumber>;
    /**
     * A list of customer contact addresses
     */
    addresses?: Array<ContactAddress>;
    /**
     * A list of internet references
     */
    internetReferences?: Array<InternetReference>;
    /**
     * A map of dynamic attributes
     */
    dynamicAttributes?: { [key: string]: DynamicAttributeValue; };
}

