/**
 * miles-customer
 * This service is used to retrieve information about customers, fleet managers,    drivers & legal entity groups.    It can manage all things related to UBO and its documents.    Customers can be created, updated and links to them can be removed.    The service provides filters needed to manage all these objects.
 *
 * The version of the OpenAPI document: 1.128.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InternetReferenceRequest } from './internet-reference-request';
import { EnumValue } from './enum-value';
import { SimpleEnumValue } from './simple-enum-value';
import { IndividualPersonRequest } from './individual-person-request';
import { AddressRequest } from './address-request';
import { SimpleDynamicAttributeValue } from './simple-dynamic-attribute-value';
import { PhoneNumberRequest } from './phone-number-request';


export interface CreateCustomerRequest { 
    /**
     * Company name. Property optional only for individual customers, required for non individual customers e.g. Organization
     */
    name?: string;
    /**
     * Official registration
     */
    officialRegistration?: string;
    /**
     * VAT number
     */
    vatNumber?: string;
    /**
     * Establishment date
     */
    establishmentDate?: string;
    taxLiability?: EnumValue;
    legalEntity: EnumValue;
    individualPerson?: IndividualPersonRequest;
    /**
     * Additional customer reference. Typically used for mapping to other systems.
     */
    reference?: string;
    /**
     * Deprecated since 2022-08-12 and version \'1.60.0\' in favor of \'individualPerson.placeOfBirth\'
     */
    placeOfBirth?: string;
    /**
     * A list of addresses
     */
    addresses?: Array<AddressRequest>;
    /**
     * A list of phone numbers
     */
    phoneNumbers?: Array<PhoneNumberRequest>;
    /**
     * A list of internet references
     */
    internetReferences: Array<InternetReferenceRequest>;
    /**
     * Broker company ID to which the customer is linked
     */
    brokerCompanyId?: string;
    /**
     * The sector code field in which to store the industrial sector classification code
     */
    sectorCode?: string;
    /**
     * Car fleet size
     */
    carFleetSize?: number;
    /**
     * Commercial fleet size
     */
    commercialFleetSize?: number;
    /**
     * A map of dynamic attributes
     */
    dynamicAttributes?: { [key: string]: SimpleDynamicAttributeValue; };
    knowYourCustomerSource?: SimpleEnumValue;
}

