/**
 * miles-customer
 * This service is used to retrieve information about customers, fleet managers,    drivers & legal entity groups.    It can manage all things related to UBO and its documents.    Customers can be created, updated and links to them can be removed.    The service provides filters needed to manage all these objects.
 *
 * The version of the OpenAPI document: 1.128.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BrokerCompanyReference } from './broker-company-reference';
import { ContactAddress } from './contact-address';
import { DynamicAttributeValue } from './dynamic-attribute-value';
import { EnumValue } from './enum-value';
import { PhoneNumber } from './phone-number';
import { SectorCodeInfo } from './sector-code-info';
import { IndividualPerson } from './individual-person';
import { InternetReference } from './internet-reference';


export interface CreateCustomerResponse { 
    /**
     * The ID of the customer
     */
    customerId?: string;
    /**
     * Trading name
     */
    tradingName?: string;
    /**
     * Legal name
     */
    legalName?: string;
    /**
     * Official registration
     */
    officialRegistration?: string;
    /**
     * VAT number
     */
    vatNumber?: string;
    /**
     * Establishment date
     */
    establishmentDate?: string;
    legalEntity?: EnumValue;
    taxLiability?: EnumValue;
    customerState?: EnumValue;
    individualPerson?: IndividualPerson;
    /**
     * A list of phone numbers
     */
    phoneNumbers?: Array<PhoneNumber>;
    /**
     * A list of customer contact addresses
     */
    addresses?: Array<ContactAddress>;
    /**
     * A list of internet references
     */
    internetReferences?: Array<InternetReference>;
    sectorCodeInfo?: SectorCodeInfo;
    /**
     * A map of dynamic attributes
     */
    dynamicAttributes?: { [key: string]: DynamicAttributeValue; };
    /**
     * Internal company code
     */
    companyGroupReference?: string;
    /**
     * Car fleet size
     */
    carFleetSize?: number;
    /**
     * Commercial fleet size
     */
    commercialFleetSize?: number;
    knowYourCustomerSource?: EnumValue;
    /**
     * A list of the broker companies to which this customer is linked
     */
    brokerCompanies?: Array<BrokerCompanyReference>;
}

