/**
 * miles-customer
 * This service is used to retrieve information about customers, fleet managers,    drivers & legal entity groups.    It can manage all things related to UBO and its documents.    Customers can be created, updated and links to them can be removed.    The service provides filters needed to manage all these objects.
 *
 * The version of the OpenAPI document: 1.128.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InternetReferenceRequest } from './internet-reference-request';
import { EnumValue } from './enum-value';
import { IndividualPersonRequest } from './individual-person-request';
import { AddressRequest } from './address-request';
import { PhoneNumberRequest } from './phone-number-request';


export interface CreateRetailCustomerRequest { 
    /**
     * The company name. This property is optional for individual retail customers, but required for non individual retail customers such as Organization
     */
    name?: string;
    /**
     * Official registration
     */
    officialRegistration?: string;
    /**
     * VAT number
     */
    vatNumber?: string;
    legalEntity: EnumValue;
    individualPerson: IndividualPersonRequest;
    /**
     * A list of addresses
     */
    addresses: Array<AddressRequest>;
    /**
     * A list of phone numbers
     */
    phoneNumbers?: Array<PhoneNumberRequest>;
    /**
     * A list of internet references
     */
    internetReferences: Array<InternetReferenceRequest>;
}

