/**
 * miles-customer
 * This service is used to retrieve information about customers, fleet managers,    drivers & legal entity groups.    It can manage all things related to UBO and its documents.    Customers can be created, updated and links to them can be removed.    The service provides filters needed to manage all these objects.
 *
 * The version of the OpenAPI document: 1.128.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DynamicAttributeValue } from './dynamic-attribute-value';
import { DefaultPhoneNumber } from './default-phone-number';
import { PrimaryAddress } from './primary-address';
import { EnumValue } from './enum-value';
import { FindPhoneNumber } from './find-phone-number';
import { CustomerContactAddress } from './customer-contact-address';
import { FindContactAddress } from './find-contact-address';
import { PersonReference } from './person-reference';
import { InternetReference } from './internet-reference';
import { EmailAddress } from './email-address';


export interface FindCustomer { 
    /**
     * The ID of the customer
     */
    customerId?: string;
    /**
     * The business unit legal name
     */
    businessUnitLegalName?: string;
    /**
     * Trading name
     */
    tradingName?: string;
    /**
     * VAT number
     */
    vatNumber?: string;
    /**
     * Reference
     */
    reference?: string;
    /**
     * Official registration
     */
    officialRegistration?: string;
    legalEntity?: EnumValue;
    /**
     * Whether the customer is a fleet customer
     */
    isFleetCustomer?: boolean;
    /**
     * Whether the customer has a fleet manager assigned
     */
    isFleetManagerAssigned?: boolean;
    /**
     * A list of phone numbers
     */
    phoneNumbers?: Array<FindPhoneNumber>;
    /**
     * A list of customer contact addresses
     */
    addresses?: Array<FindContactAddress>;
    /**
     * A list of internet references
     */
    internetReferences?: Array<InternetReference>;
    /**
     * Deprecated since 2021-11-16 and version 1.37.0 in favor of addresses
     */
    customerAddresses?: Array<CustomerContactAddress>;
    primaryAddress?: PrimaryAddress;
    defaultPhoneNumber?: DefaultPhoneNumber;
    email?: EmailAddress;
    individualPerson?: PersonReference;
    /**
     * A map of dynamic attributes
     */
    dynamicAttributes?: { [key: string]: DynamicAttributeValue; };
}

