/**
 * miles-customer
 * This service is used to retrieve information about customers, fleet managers,    drivers & legal entity groups.    It can manage all things related to UBO and its documents.    Customers can be created, updated and links to them can be removed.    The service provides filters needed to manage all these objects.
 *
 * The version of the OpenAPI document: 1.128.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DynamicAttributeValue } from './dynamic-attribute-value';
import { EnumValue } from './enum-value';


/**
 * The person related to the UBO
 */
export interface FindPerson { 
    /**
     * The ID of the person
     */
    personId?: string;
    /**
     * The first name of the person
     */
    firstName?: string;
    /**
     * The last name of the person
     */
    lastName?: string;
    /**
     * Maiden name of the person
     */
    maidenName?: string;
    /**
     * Maiden middle name of the person
     */
    maidenMiddleName?: string;
    /**
     * Maiden second last name of the person
     */
    maidenSecondLastName?: string;
    /**
     * The place of birth the person
     */
    placeOfBirth?: string;
    /**
     * The date of birth the person
     */
    dateOfBirth?: string;
    personTitle?: EnumValue;
    gender?: EnumValue;
    /**
     * The official registration of the person
     */
    officialRegistration?: string;
    /**
     * A map of dynamic attributes
     */
    dynamicAttributes?: { [key: string]: DynamicAttributeValue; };
}

