/**
 * miles-customer
 * This service is used to retrieve information about customers, fleet managers,    drivers & legal entity groups.    It can manage all things related to UBO and its documents.    Customers can be created, updated and links to them can be removed.    The service provides filters needed to manage all these objects.
 *
 * The version of the OpenAPI document: 1.128.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DynamicAttributeValue } from './dynamic-attribute-value';
import { EnumValue } from './enum-value';
import { Country } from './country';


/**
 * Individual person of customer
 */
export interface M2MIndividualPerson { 
    /**
     * ID of the person
     */
    personId?: string;
    /**
     * First name of the person
     */
    firstName?: string;
    /**
     * Middle name of the person
     */
    middleName?: string;
    /**
     * Last name of the person
     */
    lastName?: string;
    /**
     * Second last name
     */
    secondLastName?: string;
    /**
     * Maiden name of the person
     */
    maidenName?: string;
    /**
     * Maiden middle name of the person
     */
    maidenMiddleName?: string;
    /**
     * Maiden second last name of the person
     */
    maidenSecondLastName?: string;
    /**
     * Initials of the person
     */
    initials?: string;
    gender?: EnumValue;
    /**
     * Birth date
     */
    birthDate?: string;
    personTitle?: EnumValue;
    /**
     * Official registration
     */
    officialRegistration?: string;
    countryOfBirth?: Country;
    residencyStatus?: EnumValue;
    housingTenure?: EnumValue;
    /**
     * A map of dynamic attributes
     */
    dynamicAttributes?: { [key: string]: DynamicAttributeValue; };
    communicationMeduim?: EnumValue;
    communicationMedium?: EnumValue;
    /**
     * Country ID
     */
    countryId?: string;
    /**
     * Place of birth
     */
    placeOfBirth?: string;
    /**
     * Death date
     */
    deathDate?: string;
    /**
     * Full name
     */
    fullName?: string;
}

