/**
 * miles-customer
 * This service is used to retrieve information about customers, fleet managers,    drivers & legal entity groups.    It can manage all things related to UBO and its documents.    Customers can be created, updated and links to them can be removed.    The service provides filters needed to manage all these objects.
 *
 * The version of the OpenAPI document: 1.128.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DynamicAttributeValue } from './dynamic-attribute-value';
import { EnumValue } from './enum-value';
import { SimpleEnumValue } from './simple-enum-value';


/**
 * Payment preference
 */
export interface PaymentPreference { 
    /**
     * Payment Preference ID
     */
    paymentPreferenceId?: string;
    /**
     * Bank account ID
     */
    bankAccountId?: string;
    paymentMethod?: EnumValue;
    preferenceStatus?: EnumValue;
    /**
     * Reference
     */
    reference?: string;
    /**
     * Valid from
     */
    validFrom?: string;
    /**
     * Valid to
     */
    validTo?: string;
    /**
     * Indicates if payment is preferred
     */
    isPreferred?: boolean;
    preferenceType?: SimpleEnumValue;
    /**
     * Leasing company ID
     */
    leasingCompanyId?: string;
    /**
     * A map of dynamic attributes
     */
    dynamicAttributes?: { [key: string]: DynamicAttributeValue; };
}

