/**
 * miles-customer
 * This service is used to retrieve information about customers, fleet managers,    drivers & legal entity groups.    It can manage all things related to UBO and its documents.    Customers can be created, updated and links to them can be removed.    The service provides filters needed to manage all these objects.
 *
 * The version of the OpenAPI document: 1.128.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SimpleEnumValue } from './simple-enum-value';


/**
 * Phone number
 */
export interface PhoneNumberUpdateRequest { 
    /**
     * The ID of the phone number
     */
    phoneNumberId?: string;
    /**
     * The country code
     */
    country?: string;
    /**
     * The phone number
     */
    number?: string;
    /**
     * The zonal phone number
     */
    zonalPhoneNumber?: string;
    phoneType?: SimpleEnumValue;
    /**
     * Indicates whether the phone number needs to be deleted
     */
    isDeleted?: boolean;
}

