/**
 * miles-customer
 * This service is used to retrieve information about customers, fleet managers,    drivers & legal entity groups.    It can manage all things related to UBO and its documents.    Customers can be created, updated and links to them can be removed.    The service provides filters needed to manage all these objects.
 *
 * The version of the OpenAPI document: 1.128.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ContactAddress } from './contact-address';
import { DynamicAttributeValue } from './dynamic-attribute-value';
import { Language } from './language';
import { EnumValue } from './enum-value';
import { PhoneNumber } from './phone-number';
import { IndividualPerson } from './individual-person';
import { InternetReference } from './internet-reference';


/**
 * The retail customer
 */
export interface RetailCustomer { 
    /**
     * The ID of the customer
     */
    customerId?: string;
    /**
     * Trading name
     */
    tradingName?: string;
    /**
     * Official registration
     */
    officialRegistration?: string;
    /**
     * VAT number
     */
    vatNumber?: string;
    legalEntity?: EnumValue;
    language?: Language;
    individualPerson?: IndividualPerson;
    /**
     * A list of phone numbers
     */
    phoneNumbers?: Array<PhoneNumber>;
    /**
     * A list of customer contact addresses
     */
    addresses?: Array<ContactAddress>;
    /**
     * A list of internet references
     */
    internetReferences?: Array<InternetReference>;
    /**
     * A map of dynamic attributes
     */
    dynamicAttributes?: { [key: string]: DynamicAttributeValue; };
}

