/**
 * miles-customer
 * This service is used to retrieve information about customers, fleet managers,    drivers & legal entity groups.    It can manage all things related to UBO and its documents.    Customers can be created, updated and links to them can be removed.    The service provides filters needed to manage all these objects.
 *
 * The version of the OpenAPI document: 1.128.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InternetReferenceUpdateRequest } from './internet-reference-update-request';
import { ContactAddressUpdateRequest } from './contact-address-update-request';
import { PhoneNumberUpdateRequest } from './phone-number-update-request';
import { CreatePersonRequest } from './create-person-request';
import { SimpleDynamicAttributeValue } from './simple-dynamic-attribute-value';


export interface UpdateUBORequest { 
    /**
     * The ID of the contact
     */
    contactId?: string;
    /**
     * Indicates wether the UBO is politically exposed
     */
    politicalExposed?: boolean;
    /**
     * The date until which the UBO is valid, provided date included/excluded
     */
    validToDate?: string;
    person?: CreatePersonRequest;
    /**
     * A list of addresses
     */
    addresses?: Array<ContactAddressUpdateRequest>;
    /**
     * A list of phone numbers
     */
    phoneNumbers?: Array<PhoneNumberUpdateRequest>;
    /**
     * A list of internet references
     */
    internetReferences?: Array<InternetReferenceUpdateRequest>;
    /**
     * A map of dynamic attributes for the UBO contact
     */
    dynamicAttributes?: { [key: string]: SimpleDynamicAttributeValue; };
}

