/**
 * miles-customer
 * This service is used to retrieve information about customers, fleet managers,    drivers & legal entity groups.    It can manage all things related to UBO and its documents.    Customers can be created, updated and links to them can be removed.    The service provides filters needed to manage all these objects.
 *
 * The version of the OpenAPI document: 1.128.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InternetReferenceUpdateRequest } from './internet-reference-update-request';
import { ContactAddressUpdateRequest } from './contact-address-update-request';
import { PhoneNumberUpdateRequest } from './phone-number-update-request';
import { SimpleDynamicAttributeValue } from './simple-dynamic-attribute-value';
import { ContactPersonRequest } from './contact-person-request';


export interface UpdateContactRequest { 
    /**
     * The date on which the contact started at the customer
     */
    joinDate?: string;
    /**
     * The date on which the contact left the customer
     */
    leaveDate?: string;
    /**
     * Identification of the contact
     */
    identification?: string;
    /**
     * Job title of the contact
     */
    jobTitle?: string;
    /**
     * Employee number of the contact
     */
    employeeNumber?: string;
    /**
     * Additional comments for the contact
     */
    comments?: string;
    /**
     * A list of contact role IDs to be set on the contact
     */
    contactRoleIds?: Array<string>;
    person?: ContactPersonRequest;
    /**
     * A list of addresses
     */
    addresses?: Array<ContactAddressUpdateRequest>;
    /**
     * A list of phone numbers
     */
    phoneNumbers?: Array<PhoneNumberUpdateRequest>;
    /**
     * A list of internet references
     */
    internetReferences?: Array<InternetReferenceUpdateRequest>;
    /**
     * A map of dynamic attributes
     */
    dynamicAttributes?: Array<{ [key: string]: SimpleDynamicAttributeValue; }>;
}

