/**
 * miles-credit-retail
 * This functional service supports the creation and follow-up of **credit applications**.    For more information, check the **Read Me** tab.
 *
 * The version of the OpenAPI document: 1.29.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent, HttpParameterCodec, HttpContext 
        }       from '@angular/common/http';
import { CustomHttpParameterCodec }                          from '../encoder';
import { Observable }                                        from 'rxjs';

// @ts-ignore
import { ExceptionInfoDTO } from '../model/exception-info-dto';
// @ts-ignore
import { FileUploadRequest } from '../model/file-upload-request';
// @ts-ignore
import { M2MUploadApplicantCreditScoreStipulationDocumentResponse } from '../model/m2-m-upload-applicant-credit-score-stipulation-document-response';
// @ts-ignore
import { M2MUploadCreditApplicationStipulationDocumentResponse } from '../model/m2-m-upload-credit-application-stipulation-document-response';
// @ts-ignore
import { WarningsInfoDTO } from '../model/warnings-info-dto';

// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';



@Injectable({
  providedIn: 'root'
})
export class M2MCreditApplicationResourceService {

    protected basePath = 'http://localhost';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();
    public encoder: HttpParameterCodec;

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string|string[], @Optional() configuration: Configuration) {
        if (configuration) {
            this.configuration = configuration;
        }
        if (typeof this.configuration.basePath !== 'string') {
            if (Array.isArray(basePath) && basePath.length > 0) {
                basePath = basePath[0];
            }

            if (typeof basePath !== 'string') {
                basePath = this.basePath;
            }
            this.configuration.basePath = basePath;
        }
        this.encoder = this.configuration.encoder || new CustomHttpParameterCodec();
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }

    // @ts-ignore
    private addToHttpParams(httpParams: HttpParams, value: any, key?: string): HttpParams {
        if (typeof value === "object" && value instanceof Date === false) {
            httpParams = this.addToHttpParamsRecursive(httpParams, value);
        } else {
            httpParams = this.addToHttpParamsRecursive(httpParams, value, key);
        }
        return httpParams;
    }

    private addToHttpParamsRecursive(httpParams: HttpParams, value?: any, key?: string): HttpParams {
        if (value == null) {
            return httpParams;
        }

        if (typeof value === "object") {
            if (Array.isArray(value)) {
                (value as any[]).forEach( elem => httpParams = this.addToHttpParamsRecursive(httpParams, elem, key));
            } else if (value instanceof Date) {
                if (key != null) {
                    httpParams = httpParams.append(key, (value as Date).toISOString().substring(0, 10));
                } else {
                   throw Error("key may not be null if value is Date");
                }
            } else {
                Object.keys(value).forEach( k => httpParams = this.addToHttpParamsRecursive(
                    httpParams, value[k], key != null ? `${key}.${k}` : k));
            }
        } else if (key != null) {
            httpParams = httpParams.append(key, value);
        } else {
            throw Error("key may not be null if value is not object or array");
        }
        return httpParams;
    }

    /**
     * Upload documents to a specific stipulation of an applicant\&#39;s credit score
     * This endpoint uploads one or more documents to a specific stipulation of an applicant\&#39;s credit score with the possibility to control the stipulation state based on an external verification status. It is intended for machine-to-machine integrations.
     * @param creditApplicationId ID of the credit application
     * @param applicantCreditScoreId ID of the applicant credit score
     * @param stipulationTypeId The type ID of the stipulation to which documents are uploaded and for which the external verification can be updated
     * @param files The files to be attached to the stipulation
     * @param externalVerificationId Deposit external verification ID
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public uploadApplicantCreditScoreStipulationDocument1(creditApplicationId: string, applicantCreditScoreId: string, stipulationTypeId: string, files: Array<FileUploadRequest>, externalVerificationId?: string, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<M2MUploadApplicantCreditScoreStipulationDocumentResponse>;
    public uploadApplicantCreditScoreStipulationDocument1(creditApplicationId: string, applicantCreditScoreId: string, stipulationTypeId: string, files: Array<FileUploadRequest>, externalVerificationId?: string, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<M2MUploadApplicantCreditScoreStipulationDocumentResponse>>;
    public uploadApplicantCreditScoreStipulationDocument1(creditApplicationId: string, applicantCreditScoreId: string, stipulationTypeId: string, files: Array<FileUploadRequest>, externalVerificationId?: string, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<M2MUploadApplicantCreditScoreStipulationDocumentResponse>>;
    public uploadApplicantCreditScoreStipulationDocument1(creditApplicationId: string, applicantCreditScoreId: string, stipulationTypeId: string, files: Array<FileUploadRequest>, externalVerificationId?: string, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (creditApplicationId === null || creditApplicationId === undefined) {
            throw new Error('Required parameter creditApplicationId was null or undefined when calling uploadApplicantCreditScoreStipulationDocument1.');
        }
        if (applicantCreditScoreId === null || applicantCreditScoreId === undefined) {
            throw new Error('Required parameter applicantCreditScoreId was null or undefined when calling uploadApplicantCreditScoreStipulationDocument1.');
        }
        if (stipulationTypeId === null || stipulationTypeId === undefined) {
            throw new Error('Required parameter stipulationTypeId was null or undefined when calling uploadApplicantCreditScoreStipulationDocument1.');
        }
        if (files === null || files === undefined) {
            throw new Error('Required parameter files was null or undefined when calling uploadApplicantCreditScoreStipulationDocument1.');
        }

        let localVarHeaders = this.defaultHeaders;

        let localVarCredential: string | undefined;
        // authentication (Roles) required
        localVarCredential = this.configuration.lookupCredential('Roles');
        if (localVarCredential) {
        }

        let localVarHttpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
        if (localVarHttpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
                'application/json'
            ];
            localVarHttpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        let localVarHttpContext: HttpContext | undefined = options && options.context;
        if (localVarHttpContext === undefined) {
            localVarHttpContext = new HttpContext();
        }

        let localVarTransferCache: boolean | undefined = options && options.transferCache;
        if (localVarTransferCache === undefined) {
            localVarTransferCache = true;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'multipart/form-data'
        ];

        const canConsumeForm = this.canConsumeForm(consumes);

        let localVarFormParams: { append(param: string, value: any): any; };
        let localVarUseForm = false;
        let localVarConvertFormParamsToString = false;
        if (localVarUseForm) {
            localVarFormParams = new FormData();
        } else {
            localVarFormParams = new HttpParams({encoder: this.encoder});
        }

        if (stipulationTypeId !== undefined) {
            localVarFormParams = localVarFormParams.append('stipulationTypeId', <any>stipulationTypeId) as any || localVarFormParams;
        }
        if (externalVerificationId !== undefined) {
            localVarFormParams = localVarFormParams.append('externalVerificationId', <any>externalVerificationId) as any || localVarFormParams;
        }
        if (files) {
            if (localVarUseForm) {
                files.forEach((element) => {
                    localVarFormParams = localVarFormParams.append('files', <any>element) as any || localVarFormParams;
            })
            } else {
                localVarFormParams = localVarFormParams.append('files', [...files].join(COLLECTION_FORMATS['csv'])) as any || localVarFormParams;
            }
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/m2m/credit-applications/${this.configuration.encodeParam({name: "creditApplicationId", value: creditApplicationId, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}/applicant-credit-scores/${this.configuration.encodeParam({name: "applicantCreditScoreId", value: applicantCreditScoreId, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}/stipulations/documents`;
        return this.httpClient.request<M2MUploadApplicantCreditScoreStipulationDocumentResponse>('post', `${this.configuration.basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                body: localVarConvertFormParamsToString ? localVarFormParams.toString() : localVarFormParams,
                responseType: <any>responseType_,
                withCredentials: this.configuration.withCredentials,
                headers: localVarHeaders,
                observe: observe,
                transferCache: localVarTransferCache,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Upload documents to a specific stipulation
     * This endpoint uploads one or more documents to a specific stipulation with the possibility to control the stipulation state based on an external verification status. It is intended for machine-to-machine integrations.
     * @param creditApplicationId ID of the credit application
     * @param stipulationTypeId The type ID of the stipulation to which documents are uploaded and for which the external verification can be updated
     * @param files The files to be attached to the stipulation
     * @param externalVerificationId Deposit external verification ID
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public uploadCreditApplicationStipulationDocument1(creditApplicationId: string, stipulationTypeId: string, files: Array<FileUploadRequest>, externalVerificationId?: string, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<M2MUploadCreditApplicationStipulationDocumentResponse>;
    public uploadCreditApplicationStipulationDocument1(creditApplicationId: string, stipulationTypeId: string, files: Array<FileUploadRequest>, externalVerificationId?: string, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<M2MUploadCreditApplicationStipulationDocumentResponse>>;
    public uploadCreditApplicationStipulationDocument1(creditApplicationId: string, stipulationTypeId: string, files: Array<FileUploadRequest>, externalVerificationId?: string, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<M2MUploadCreditApplicationStipulationDocumentResponse>>;
    public uploadCreditApplicationStipulationDocument1(creditApplicationId: string, stipulationTypeId: string, files: Array<FileUploadRequest>, externalVerificationId?: string, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (creditApplicationId === null || creditApplicationId === undefined) {
            throw new Error('Required parameter creditApplicationId was null or undefined when calling uploadCreditApplicationStipulationDocument1.');
        }
        if (stipulationTypeId === null || stipulationTypeId === undefined) {
            throw new Error('Required parameter stipulationTypeId was null or undefined when calling uploadCreditApplicationStipulationDocument1.');
        }
        if (files === null || files === undefined) {
            throw new Error('Required parameter files was null or undefined when calling uploadCreditApplicationStipulationDocument1.');
        }

        let localVarHeaders = this.defaultHeaders;

        let localVarCredential: string | undefined;
        // authentication (Roles) required
        localVarCredential = this.configuration.lookupCredential('Roles');
        if (localVarCredential) {
        }

        let localVarHttpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
        if (localVarHttpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
                'application/json'
            ];
            localVarHttpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        let localVarHttpContext: HttpContext | undefined = options && options.context;
        if (localVarHttpContext === undefined) {
            localVarHttpContext = new HttpContext();
        }

        let localVarTransferCache: boolean | undefined = options && options.transferCache;
        if (localVarTransferCache === undefined) {
            localVarTransferCache = true;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'multipart/form-data'
        ];

        const canConsumeForm = this.canConsumeForm(consumes);

        let localVarFormParams: { append(param: string, value: any): any; };
        let localVarUseForm = false;
        let localVarConvertFormParamsToString = false;
        if (localVarUseForm) {
            localVarFormParams = new FormData();
        } else {
            localVarFormParams = new HttpParams({encoder: this.encoder});
        }

        if (stipulationTypeId !== undefined) {
            localVarFormParams = localVarFormParams.append('stipulationTypeId', <any>stipulationTypeId) as any || localVarFormParams;
        }
        if (externalVerificationId !== undefined) {
            localVarFormParams = localVarFormParams.append('externalVerificationId', <any>externalVerificationId) as any || localVarFormParams;
        }
        if (files) {
            if (localVarUseForm) {
                files.forEach((element) => {
                    localVarFormParams = localVarFormParams.append('files', <any>element) as any || localVarFormParams;
            })
            } else {
                localVarFormParams = localVarFormParams.append('files', [...files].join(COLLECTION_FORMATS['csv'])) as any || localVarFormParams;
            }
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/m2m/credit-applications/${this.configuration.encodeParam({name: "creditApplicationId", value: creditApplicationId, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}/stipulations/documents`;
        return this.httpClient.request<M2MUploadCreditApplicationStipulationDocumentResponse>('post', `${this.configuration.basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                body: localVarConvertFormParamsToString ? localVarFormParams.toString() : localVarFormParams,
                responseType: <any>responseType_,
                withCredentials: this.configuration.withCredentials,
                headers: localVarHeaders,
                observe: observe,
                transferCache: localVarTransferCache,
                reportProgress: reportProgress
            }
        );
    }

}
