/**
 * miles-dealer-pos
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.8.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MultiCurrencyValue } from './multi-currency-value';
import { MultiLanguageValue } from './multi-language-value';
import { EnumValue } from './enum-value';
import { QualifierValue } from './qualifier-value';
import { VehicleOption } from './vehicle-option';


export interface AccessoryOption extends VehicleOption { 
    /**
     * The generic option ID
     */
    genericOptionId?: string;
    qualifier1?: QualifierValue;
    qualifier2?: QualifierValue;
    qualifier3?: QualifierValue;
}

