/**
 * miles-dealer-pos
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.8.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The unit of the age value
 */
export type AgeUnit = 'YEARS' | 'MONTHS' | 'DAYS' | 'HOURS' | 'MINUTES' | 'SECONDS';

export const AgeUnit = {
    Years: 'YEARS' as AgeUnit,
    Months: 'MONTHS' as AgeUnit,
    Days: 'DAYS' as AgeUnit,
    Hours: 'HOURS' as AgeUnit,
    Minutes: 'MINUTES' as AgeUnit,
    Seconds: 'SECONDS' as AgeUnit
};

