/**
 * miles-dealer-pos
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.8.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The reference information of the pending contract
 */
export interface AmendmentQuotePendingContractReference { 
    /**
     * The ID of the pending contract
     */
    pendingContractId?: string;
    /**
     * The reference of the pending contract
     */
    reference?: string;
}

