/**
 * miles-dealer-pos
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.8.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BrokerCompanyReference } from './broker-company-reference';
import { DynamicAttributeValue } from './dynamic-attribute-value';
import { Vehicle } from './vehicle';
import { AmendmentQuotePricing } from './amendment-quote-pricing';
import { QuotationTemplateReference } from './quotation-template-reference';
import { CustomerReference } from './customer-reference';
import { AmendmentQuotePendingContractReference } from './amendment-quote-pending-contract-reference';
import { EnumValue } from './enum-value';
import { BrokerContactReference } from './broker-contact-reference';
import { AmendmentQuoteProduct } from './amendment-quote-product';


/**
 * The amendment quote
 */
export interface AmendmentQuote { 
    /**
     * The ID of the amendment quote
     */
    amendmentQuoteId?: string;
    /**
     * The reference of the amendment quote
     */
    reference?: string;
    /**
     * A description for the amendment quote
     */
    description?: string;
    /**
     * The date on which the amendment quote is created
     */
    creationDate?: string;
    /**
     * The date on which the amendment quote will expire
     */
    expirationDate?: string;
    /**
     * The date on which the amendment quote was last modified
     */
    lastModified?: string;
    /**
     * An external reference to the request
     */
    externalRequestReference?: string;
    changeReason?: EnumValue;
    status?: EnumValue;
    customer?: CustomerReference;
    product?: AmendmentQuoteProduct;
    brokerContact?: BrokerContactReference;
    pendingContract?: AmendmentQuotePendingContractReference;
    quotationTemplate?: QuotationTemplateReference;
    vehicle?: Vehicle;
    /**
     * A list of broker companies
     */
    brokerCompanies?: Array<BrokerCompanyReference>;
    pricing?: AmendmentQuotePricing;
    /**
     * A map of dynamic attributes
     */
    dynamicAttributes?: { [key: string]: DynamicAttributeValue; };
}

