/**
 * miles-dealer-pos
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.8.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DynamicAttributeValue } from './dynamic-attribute-value';
import { ProductConfiguration } from './product-configuration';
import { AmendmentQuoteMileageTermInformation } from './amendment-quote-mileage-term-information';
import { MultiLanguageValue } from './multi-language-value';
import { EnumValue } from './enum-value';
import { AmendmentQuoteProductPricingDetails } from './amendment-quote-product-pricing-details';


/**
 * The product linked to the amendment quote
 */
export interface AmendmentQuoteProduct { 
    /**
     * The ID of the product linked to the amendment quote
     */
    productId?: string;
    description?: MultiLanguageValue;
    productCategory?: EnumValue;
    mileageAndTerm?: AmendmentQuoteMileageTermInformation;
    productPricingDetails?: AmendmentQuoteProductPricingDetails;
    productConfiguration?: ProductConfiguration;
    /**
     * A map of dynamic attributes
     */
    dynamicAttributes?: { [key: string]: DynamicAttributeValue; };
}

