/**
 * miles-dealer-pos
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.8.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { VehicleDiscount } from './vehicle-discount';
import { MultiCurrencyValue } from './multi-currency-value';
import { VatCode } from './vat-code';
import { DeliveryCostReference } from './delivery-cost-reference';


/**
 * The pricing information related to the vehicle
 */
export interface AmendmentQuoteVehiclePricing { 
    catalogPrice?: MultiCurrencyValue;
    vatCode?: VatCode;
    consumerPrice?: MultiCurrencyValue;
    totalDiscountAmountExclusiveVat?: MultiCurrencyValue;
    totalDiscountAmountInclusiveVat?: MultiCurrencyValue;
    /**
     * The discount percentage
     */
    discountPercentage?: number;
    netPriceExclusiveVat?: MultiCurrencyValue;
    netPriceInclusiveVat?: MultiCurrencyValue;
    tax?: MultiCurrencyValue;
    totalOptionPrice?: MultiCurrencyValue;
    /**
     * The list of delivery costs
     */
    deliveryCosts?: Array<DeliveryCostReference>;
    /**
     * The list of discounts
     */
    discounts?: Array<VehicleDiscount>;
}

