/**
 * miles-dealer-pos
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.8.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The reason why the amendment quote is created
 */
export interface ChangeReason { 
    /**
     * The change reason ID
     */
    id?: string;
    /**
     * The change reason description
     */
    description?: string;
}

