/**
 * miles-dealer-pos
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.8.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PendingContractDeliveryConditionsRequest } from './pending-contract-delivery-conditions-request';


export interface ConfirmPendingContractVehicleDeliveryRequest { 
    /**
     * The date and time when the vehicle was delivered
     */
    deliveryDate: string;
    /**
     * The mileage when the vehicle was delivered
     */
    mileageOnDelivery: number;
    deliveryConditions?: PendingContractDeliveryConditionsRequest;
}

