/**
 * miles-dealer-pos
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.8.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CustomerReference } from './customer-reference';
import { PendingContractDeliveryConditions } from './pending-contract-delivery-conditions';
import { EnumValue } from './enum-value';
import { VehicleInformation } from './vehicle-information';


export interface ConfirmPendingContractVehicleDeliveryResponse { 
    /**
     * The date and time when the vehicle was delivered
     */
    deliveryDate?: string;
    /**
     * The mileage when the vehicle was delivered
     */
    mileageOnDelivery?: number;
    reportStatus?: EnumValue;
    customer?: CustomerReference;
    deliveryConditions?: PendingContractDeliveryConditions;
    vehicleInformation?: VehicleInformation;
}

