/**
 * miles-dealer-pos
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.8.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MultiCurrencyValue } from './multi-currency-value';
import { MultiLanguageValue } from './multi-language-value';


export interface CreatePendingContractPurchaseInvoiceResponse { 
    /**
     * The upcoming delivery information ID
     */
    upcomingDeliveryInformationId?: string;
    /**
     * The purchase invoice ID
     */
    purchaseInvoiceId?: string;
    /**
     * The invoice number
     */
    invoiceNumber?: string;
    /**
     * The date on the invoice
     */
    invoiceDate?: string;
    /**
     * The due date of the invoice
     */
    dueDate?: string;
    /**
     * The payment date of the invoice
     */
    paymentDate?: string;
    description?: MultiLanguageValue;
    /**
     * The payment message of the invoice
     */
    paymentMessage?: string;
    /**
     * The purchase order reference linked to the invoice
     */
    purchaseOrderReference?: string;
    invoiceAmountInclVat?: MultiCurrencyValue;
    invoiceAmountExclVat?: MultiCurrencyValue;
    invoiceAmountVat?: MultiCurrencyValue;
}

