/**
 * miles-dealer-pos
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.8.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LocalTime } from './local-time';


/**
 * The default value that applies for this field when it is empty
 */
export interface DefaultValue { 
    /**
     * The text value to use as default
     */
    string?: string;
    /**
     * The enumeration value to use as default
     */
    enumId?: string;
    /**
     * The integer value to use as default
     */
    integer?: number;
    /**
     * The date to use as default
     */
    date?: string;
    /**
     * The date and time to use as default
     */
    dateTime?: string;
    time?: LocalTime;
    value?: object;
    /**
     * The long value to use as default
     */
    _long?: number;
    /**
     * The double value to use as default
     */
    _double?: number;
    /**
     * The boolean value to use as default
     */
    _boolean?: boolean;
}

