/**
 * miles-dealer-pos
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.8.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MultiCurrencyValue } from './multi-currency-value';


/**
 * A delivery cost
 */
export interface DeliveryCostReference { 
    /**
     * The ID of the delivery cost
     */
    deliveryCostId?: string;
    /**
     * The delivery cost type ID of the delivery cost
     */
    deliveryCostTypeId?: string;
    amountExclusiveVat?: MultiCurrencyValue;
    amountInclusiveVat?: MultiCurrencyValue;
}

