/**
 * miles-dealer-pos
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.8.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The discount amount or percentage
 */
export interface DiscountAmountPercentage { 
    /**
     * The discount amount. This field and the `percentage` field are mutually exclusive.
     */
    amount?: number;
    /**
     * The discount percentage is expressed as a value between 0 and 1. This field and the `amount` field are mutually exclusive.
     */
    percentage?: number;
}

