/**
 * miles-dealer-pos
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.8.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FindPendingContractStipulationDocument } from './find-pending-contract-stipulation-document';


export interface FindPendingContractStipulationDocumentsResponse { 
    /**
     * List of attached documents from pending contract stipulations
     */
    documents?: Array<FindPendingContractStipulationDocument>;
    /**
     * Number of retrieved pending contract stipulation documents
     */
    totalCount?: number;
}

