/**
 * miles-dealer-pos
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.8.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FindPendingContractPurchaseInvoiceDocument } from './find-pending-contract-purchase-invoice-document';


export interface FindPendingContractPurchaseInvoiceDocumentsResponse { 
    /**
     * List of attached documents from pending contract purchase invoices
     */
    documents?: Array<FindPendingContractPurchaseInvoiceDocument>;
    /**
     * Number of retrieved pending contract purchase documents
     */
    totalCount?: number;
}

