/**
 * miles-dealer-pos
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.8.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EnumValue } from './enum-value';


/**
 * A pending contract stipulation
 */
export interface FindPendingContractStipulation { 
    /**
     * The ID of the stipulation linked to the pending contract
     */
    stipulationId?: string;
    /**
     * The name of the stipulation linked to the pending contract
     */
    name?: string;
    stipulationType?: EnumValue;
    stipulationStatus?: EnumValue;
}

