/**
 * miles-dealer-pos
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.8.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DocumentStatus } from './document-status';
import { MultiLanguageValue } from './multi-language-value';


/**
 * A pending contract amendment quote document
 */
export interface FindPendingContractAmendmentQuoteDocument { 
    /**
     * The ID of the document
     */
    documentId?: string;
    /**
     * The file type of the document
     */
    fileType?: string;
    /**
     * The creation date of the document
     */
    creationDate?: string;
    name?: MultiLanguageValue;
    description?: MultiLanguageValue;
    documentStatus?: DocumentStatus;
}

