/**
 * miles-dealer-pos
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.8.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MileageBounds } from './mileage-bounds';
import { MultiLanguageValue } from './multi-language-value';
import { TermBounds } from './term-bounds';
import { ContractType } from './contract-type';


/**
 * A quotation template
 */
export interface FindQuotationTemplate { 
    /**
     * The quotation template ID
     */
    quotationTemplateId?: string;
    name?: MultiLanguageValue;
    contractType?: ContractType;
    mileage?: MileageBounds;
    term?: TermBounds;
    /**
     * The date from which this quotation template is valid, specified date included
     */
    availableFrom?: string;
    /**
     * The date to which this quotation template is valid, specified date excluded
     */
    availableTo?: string;
}

