/**
 * miles-dealer-pos
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.8.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DynamicAttributeValue } from './dynamic-attribute-value';
import { QuotationTemplateReference } from './quotation-template-reference';
import { CustomerReference } from './customer-reference';
import { FindAmendmentQuoteVehicle } from './find-amendment-quote-vehicle';
import { AmendmentQuotePendingContractReference } from './amendment-quote-pending-contract-reference';
import { EnumValue } from './enum-value';
import { FindAmendmentQuoteProduct } from './find-amendment-quote-product';
import { BrokerContactReference } from './broker-contact-reference';


/**
 * An amendment quote linked to the pending contract
 */
export interface FindAmendmentQuote { 
    /**
     * The ID of the amendment quote linked to a pending contract
     */
    amendmentQuoteId?: string;
    status?: EnumValue;
    /**
     * The reference of the amendment quote
     */
    reference?: string;
    pendingContract?: AmendmentQuotePendingContractReference;
    customer?: CustomerReference;
    brokerContact?: BrokerContactReference;
    /**
     * The date on which the amendment quote was created
     */
    creationDate?: string;
    /**
     * The expiration date of the amendment quote
     */
    expirationDate?: string;
    quotationTemplate?: QuotationTemplateReference;
    product?: FindAmendmentQuoteProduct;
    vehicle?: FindAmendmentQuoteVehicle;
    /**
     * The dynamic attributes of the amendment quote
     */
    dynamicAttributes?: { [key: string]: DynamicAttributeValue; };
}

