/**
 * miles-dealer-pos
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.8.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FindAmendmentQuote } from './find-amendment-quote';


export interface FindAmendmentQuotesResponse { 
    /**
     * The paginated list of amendment quotes linked to pending contracts
     */
    amendmentQuotes?: Array<FindAmendmentQuote>;
    /**
     * The number of amendment quotes linked to pending contracts that qualify for the filters
     */
    totalCount?: number;
}

