/**
 * miles-dealer-pos
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.8.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MultiLanguageValue } from './multi-language-value';
import { EnumValue } from './enum-value';


/**
 * A pending contract stipulation document
 */
export interface FindPendingContractStipulationDocument { 
    /**
     * The ID of the document
     */
    documentId?: string;
    /**
     * The ID of the stipulation to which the document is linked
     */
    stipulationId?: string;
    /**
     * The file type of the document
     */
    fileType?: string;
    /**
     * The creation date of the document
     */
    creationDate?: string;
    name?: MultiLanguageValue;
    description?: MultiLanguageValue;
    documentStatus?: EnumValue;
}

