/**
 * miles-dealer-pos
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.8.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MultiCurrencyValue } from './multi-currency-value';
import { MultiLanguageValue } from './multi-language-value';


/**
 * A pending contract purchase invoice
 */
export interface FindPendingContractPurchaseInvoice { 
    /**
     * The ID of the purchase invoice
     */
    purchaseInvoiceId?: string;
    /**
     * The ID of the linked upcoming delivery information
     */
    upcomingDeliveryInformationId?: string;
    /**
     * The date on which the invoice was sent
     */
    invoiceDate?: string;
    /**
     * The due date of the invoice
     */
    dueDate?: string;
    /**
     * The date on which the invoice was paid
     */
    paymentDate?: string;
    description?: MultiLanguageValue;
    /**
     * The number of the invoice
     */
    invoiceNumber?: string;
    /**
     * The payment message for the invoice
     */
    paymentMessage?: string;
    /**
     * The purchase order reference of the invoice
     */
    purchaseOrderReference?: string;
    invoiceAmountInclVat?: MultiCurrencyValue;
    invoiceAmountExclVat?: MultiCurrencyValue;
    invoiceAmountVat?: MultiCurrencyValue;
}

