/**
 * miles-dealer-pos
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.8.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DynamicAttributeValue } from './dynamic-attribute-value';
import { AmendmentQuoteMileageTermInformation } from './amendment-quote-mileage-term-information';
import { GetProductConfiguration } from './get-product-configuration';
import { MultiLanguageValue } from './multi-language-value';
import { ProductCategory } from './product-category';


/**
 * The product linked to the amendment quote
 */
export interface GetAmendmentQuoteProduct { 
    /**
     * The ID of the product linked to the amendment quote
     */
    productId?: string;
    description?: MultiLanguageValue;
    productCategory?: ProductCategory;
    mileageAndTerm?: AmendmentQuoteMileageTermInformation;
    productConfiguration?: GetProductConfiguration;
    /**
     * The dynamic attributes of the amendment quote product
     */
    dynamicAttributes?: { [key: string]: DynamicAttributeValue; };
}

