/**
 * miles-dealer-pos
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.8.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BrokerCompanyReference } from './broker-company-reference';
import { DynamicAttributeValue } from './dynamic-attribute-value';
import { AmendmentQuotePricing } from './amendment-quote-pricing';
import { QuotationTemplateReference } from './quotation-template-reference';
import { CustomerReference } from './customer-reference';
import { AmendmentQuotePendingContractReference } from './amendment-quote-pending-contract-reference';
import { AmendmentQuoteStatus } from './amendment-quote-status';
import { BrokerContactReference } from './broker-contact-reference';
import { GetAmendmentQuoteProduct } from './get-amendment-quote-product';
import { GetAmendmentQuoteVehicle } from './get-amendment-quote-vehicle';
import { ChangeReason } from './change-reason';


export interface GetAmendmentQuoteResponse { 
    /**
     * The ID of the amendment quote linked to a pending contract
     */
    amendmentQuoteId?: string;
    /**
     * The reference of the amendment quote
     */
    reference?: string;
    /**
     * A description for the amendment quote
     */
    description?: string;
    /**
     * An external reference to the request
     */
    externalRequestReference?: string;
    status?: AmendmentQuoteStatus;
    changeReason?: ChangeReason;
    /**
     * The date on which the amendment quote was created
     */
    creationDate?: string;
    /**
     * The expiration date of the amendment quote
     */
    expirationDate?: string;
    /**
     * The date on which the amendment quote was last modified
     */
    lastModified?: string;
    brokerContact?: BrokerContactReference;
    customer?: CustomerReference;
    pendingContract?: AmendmentQuotePendingContractReference;
    product?: GetAmendmentQuoteProduct;
    quotationTemplate?: QuotationTemplateReference;
    vehicle?: GetAmendmentQuoteVehicle;
    /**
     * A list of broker companies
     */
    brokerCompanies?: Array<BrokerCompanyReference>;
    pricing?: AmendmentQuotePricing;
    /**
     * The dynamic attributes of the amendment quote
     */
    dynamicAttributes?: { [key: string]: DynamicAttributeValue; };
}

