/**
 * miles-dealer-pos
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.8.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Indicates whether this field is required, conditionally required or optional. If the value is \'CONDITIONAL_REQUIRED\', then the field \'condition\' should have a value.
 */
export type Mandatory = 'REQUIRED' | 'CONDITIONAL' | 'OPTIONAL';

export const Mandatory = {
    Required: 'REQUIRED' as Mandatory,
    Conditional: 'CONDITIONAL' as Mandatory,
    Optional: 'OPTIONAL' as Mandatory
};

