/**
 * miles-dealer-pos
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.8.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The mileage information
 */
export interface MileageBounds { 
    /**
     * The minimum mileage that is allowed (inclusive)
     */
    minimumValue?: number;
    /**
     * The default value of the mileage
     */
    defaultValue?: number;
    /**
     * The maximum mileage that is allowed (inclusive)
     */
    maximumValue?: number;
    /**
     * Indicates whether the mileage is a required property
     */
    isMandatory?: boolean;
}

