/**
 * miles-dealer-pos
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.8.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MultiLanguageValue } from './multi-language-value';


/**
 * The model of the vehicle
 */
export interface Model { 
    /**
     * The ID of the model
     */
    modelId?: string;
    name?: MultiLanguageValue;
    /**
     * The year of the model
     */
    year?: string;
}

