/**
 * miles-dealer-pos
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.8.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DiscountAmountPercentage } from './discount-amount-percentage';


/**
 * A discount that should be added or updated
 */
export interface ModifyDiscount { 
    /**
     * The ID of the discount type
     */
    discountTypeId: string;
    discount: DiscountAmountPercentage;
}

