/**
 * miles-dealer-pos
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.8.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AndConditionAndInner } from './and-condition-and-inner';


export interface OrCondition { 
    /**
     * The conditions to combine with the OR logical operator, an empty list of conditions evaluates to FALSE
     */
    or?: Array<AndConditionAndInner>;
}

