/**
 * miles-dealer-pos
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.8.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The originating quote information of the pending contract
 */
export interface OriginatingQuoteReference { 
    /**
     * The ID of the originating quote
     */
    originatingQuoteId?: string;
    /**
     * The reference of the originating quote
     */
    originatingQuoteReference?: string;
}

