/**
 * miles-dealer-pos
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.8.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The conditions of the vehicle that was delivered
 */
export interface PendingContractDeliveryConditionsRequest { 
    /**
     * The number of keys delivered with the vehicle
     */
    numberOfKeys?: number;
    /**
     * The number of immobilizers delivered with the vehicle
     */
    numberOfImmobilizers?: number;
    /**
     * Indicates whether the vehicle was delivered with the agreed accessories
     */
    isAccessoriesOk?: boolean;
    /**
     * Indicates whether the vehicle was delivered with the agreed documents
     */
    isDocumentsOk?: boolean;
}

