/**
 * miles-dealer-pos
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.8.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Service } from './service';
import { ServicePricingDetail } from './service-pricing-detail';


/**
 * The configuration of the product linked to the amendment quote
 */
export interface ProductConfiguration { 
    /**
     * The reference of the product
     */
    reference?: string;
    /**
     * A list of services
     */
    services?: Array<Service>;
    /**
     * Deprecated since 2024-03-21 and version \'1.8.0\' in favor of \'amendmentQuote.pricing.product.services\'. A list of service pricing details.
     */
    servicesPriceDetails?: Array<ServicePricingDetail>;
}

