/**
 * miles-dealer-pos
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.8.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Miles API v1 representation of a qualifier value.
 */
export interface QualifierValue { 
    /**
     * The name of the qualifier value
     */
    name?: string;
    /**
     * The multi-language ID that can be used to retrieve the translation in other languages
     */
    multiLanguageId?: string;
    /**
     * The type of the qualifier
     */
    qualifierType?: string;
    /**
     * Based on this integer the \'value\' will consist of a value matching these types:   * 1  = MultiLanguageValue   * 2  = EnumValue   * 3  = MultiCurrencyValue   * 4  = DoubleUnitValue   * 5  = IntegerUnitValue   * 6  = StringValue   * 7  = IntegerValue   * 8  = DoubleValue   * 9  = BooleanValue   * 10 = UnnamedValue   * 11 = DateValue   * 12 = TimeValue   * 13 = DateTimeValue   * 14 = ZonedDateTimeValue   * 15 = LongValue  
     */
    valueType?: number;
    /**
     * An object that contains the actual value
     */
    value?: object;
    translation?: string;
}

