/**
 * miles-dealer-pos
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.8.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The attribute on the amendment quote that will be impacted by the recalculation to match the targeted lease price
 */
export type RecalculationAttribute = 'CUSTOMER_UPFRONT' | 'DRIVER_UPFRONT' | 'DEALER_DISCOUNT_AMOUNT' | 'RESIDUAL_VALUE';

export const RecalculationAttribute = {
    CustomerUpfront: 'CUSTOMER_UPFRONT' as RecalculationAttribute,
    DriverUpfront: 'DRIVER_UPFRONT' as RecalculationAttribute,
    DealerDiscountAmount: 'DEALER_DISCOUNT_AMOUNT' as RecalculationAttribute,
    ResidualValue: 'RESIDUAL_VALUE' as RecalculationAttribute
};

