/**
 * miles-dealer-pos
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.8.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Recipients } from './recipients';


/**
 * The information needed to send the pending contract amendment quote email
 */
export interface SendMailAmendmentQuoteRequest { 
    /**
     * The ID of the document that needs to be attached to the email
     */
    attachmentDocumentId?: string;
    /**
     * The subject of the email
     */
    subject: string;
    /**
     * The body of the email
     */
    body: string;
    recipients: Recipients;
}

