/**
 * miles-dealer-pos
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.8.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { QualifierSettingUpdate } from './qualifier-setting-update';


/**
 * A service to update on the pending contract via the amendment quote
 */
export interface ServiceUpdate { 
    /**
     * The ID of the service
     */
    serviceId: string;
    /**
     * The ID of the selected service choice
     */
    selectedServiceChoiceId: string;
    /**
     * The list of qualifier settings to update on the service
     */
    qualifierSettings?: Array<QualifierSettingUpdate>;
}

