/**
 * miles-dealer-pos
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.8.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { QualifierSetting } from './qualifier-setting';
import { ServiceChoice } from './service-choice';


/**
 * A service
 */
export interface Service { 
    /**
     * The ID of the service
     */
    serviceId?: string;
    /**
     * A list of service choices
     */
    choices?: Array<ServiceChoice>;
    /**
     * A list of qualifier settings
     */
    qualifierSettings?: Array<QualifierSetting>;
}

