/**
 * miles-dealer-pos
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.8.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MultiCurrencyValue } from './multi-currency-value';
import { MultiLanguageValue } from './multi-language-value';


/**
 * A service choice of the service
 */
export interface ServiceChoice { 
    /**
     * The ID of the service choice
     */
    serviceChoiceId?: string;
    label?: MultiLanguageValue;
    /**
     * Indicates whether the service choice is selected
     */
    isSelected?: boolean;
    leasePrice?: MultiCurrencyValue;
    leaseVat?: MultiCurrencyValue;
}

