/**
 * miles-dealer-pos
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.8.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The changes to the mileage and/or term of the pending contract via an amendment quote
 */
export interface UpdateAmendmentQuoteMileageTerm { 
    /**
     * The term to use in the recalculation of the pending contract via an amendment quote
     */
    term?: number;
    /**
     * The total mileage to use in the recalculation of the pending contract via an amendment quote
     */
    totalMileage?: number;
}

