/**
 * miles-dealer-pos
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.8.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type ValidationRulesCategory = 'PENDING_CONTRACT_REGISTER_LICENSE_PLATE';

export const ValidationRulesCategory = {
    PendingContractRegisterLicensePlate: 'PENDING_CONTRACT_REGISTER_LICENSE_PLATE' as ValidationRulesCategory
};

