/**
 * miles-dealer-pos
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.8.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * A possible solution
 */
export interface VehicleOptionSolution { 
    /**
     * Solution message
     */
    message?: string;
    /**
     * A list of IDs of the factory options you need to select for this solution
     */
    includeFactoryOptionIds?: Array<string>;
    /**
     * A list of IDs of the vehicle options you need to remove for this solution
     */
    excludeVehicleOptionIds?: Array<string>;
}

