/**
 * miles-dealer-pos
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.8.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { VehicleOption } from './vehicle-option';


/**
 * The configuration information of the vehicle
 */
export interface VehicleConfigurationInformation { 
    /**
     * A list of options for the vehicle
     */
    vehicleOptions?: Array<VehicleOption>;
    /**
     * The configuration date of the vehicle
     */
    configurationDate?: string;
    /**
     * The date when the configuration changed for the last time
     */
    configurationChangedDate?: string;
    /**
     * The date when the configuration has been validated for the last time
     */
    validationDate?: string;
}

