/**
 * miles-dealer-pos
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.8.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MultiLanguageValue } from './multi-language-value';
import { EnumValue } from './enum-value';
import { SupplierReference } from './supplier-reference';


/**
 * The delivery details of the vehicle
 */
export interface VehicleDeliveryDetails { 
    registrationCode?: EnumValue;
    /**
     * The date on which the delivery has been requested to happen
     */
    requestedDeliveryDate?: string;
    /**
     * The requested delivery location
     */
    requestedDeliveryLocation?: string;
    registrationRegion?: MultiLanguageValue;
    supplier?: SupplierReference;
}

