/**
 * miles-dealer-pos
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.8.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { VehicleOptionSolution } from './vehicle-option-solution';


/**
 * A vehicle option violation
 */
export interface VehicleOptionViolation { 
    /**
     * Indicates whether the violation can be automatically solved
     */
    isAutomaticalSolvable?: boolean;
    /**
     * The message explaining the violation
     */
    message?: string;
    /**
     * A list of possible solutions to resolve the violation
     */
    solutions?: Array<VehicleOptionSolution>;
}

