/**
 * miles-catalog
 * This service may be used to retrieve for    makes, models, catalog vehicles and catalog options. Also generic    options can be retrieved for colors and accessories. Finally, also    vehicle images are available through this service.
 *
 * The version of the OpenAPI document: 2.35.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MultiCurrencyValue } from './multi-currency-value';
import { DoubleUnitValue } from './double-unit-value';
import { GenericOption } from './generic-option';
import { MultiLanguageValue } from './multi-language-value';
import { EnumValue } from './enum-value';
import { CatalogVehicleReference } from './catalog-vehicle-reference';


export interface CatalogOption { 
    /**
     * The ID of the catalog option
     */
    catalogOptionId?: string;
    annotation?: MultiLanguageValue;
    /**
     * The start date from which the catalog option is available
     */
    availableFrom?: string;
    /**
     * The end date to which the catalog option is available
     */
    availableTo?: string;
    /**
     * If the catalog option supports automatic selection
     */
    automaticSelection?: boolean;
    /**
     * The ID of the type of the catalog option
     */
    catalogOptionTypeId?: string;
    catalogPrice?: MultiCurrencyValue;
    consumerPrice?: MultiCurrencyValue;
    /**
     * The default discount percentage of the catalog option
     */
    defaultDiscountPercentage?: number;
    defaultDiscountAmount?: MultiCurrencyValue;
    deliveryCost?: MultiCurrencyValue;
    description?: MultiLanguageValue;
    /**
     * The reference of the catalog option
     */
    reference?: string;
    /**
     * If the catalog option is standard
     */
    isStandard?: boolean;
    maintenanceCost?: MultiCurrencyValue;
    netWeight?: DoubleUnitValue;
    /**
     * The delivery cost of the catalog option
     */
    optionCode?: string;
    /**
     * The residual value coefficient of the catalog option
     */
    residualValueCoefficient?: number;
    /**
     * The residual value percentage of the catalog option
     */
    residualValuePercentage?: number;
    tax?: MultiCurrencyValue;
    /**
     * The tax percentage of the catalog option
     */
    taxPercentage?: number;
    /**
     * The tire specification of the catalog option
     */
    tireSpecification?: string;
    optionUse?: EnumValue;
    catalogVatCode?: EnumValue;
    deliveryVatCode?: EnumValue;
    optionType?: EnumValue;
    catalogVehicle?: CatalogVehicleReference;
    /**
     * The sub-packs that are contained by this pack
     */
    catalogOptionPacks?: Array<CatalogOption>;
    /**
     * The options that are contained by this pack
     */
    catalogOptions?: Array<CatalogOption>;
    /**
     * The generic options that are contained by this pack
     */
    genericOptions?: Array<GenericOption>;
}

