/**
 * miles-catalog
 * This service may be used to retrieve for    makes, models, catalog vehicles and catalog options. Also generic    options can be retrieved for colors and accessories. Finally, also    vehicle images are available through this service.
 *
 * The version of the OpenAPI document: 2.35.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Miles API v1 representation of an enum value. It contains additional values representing the attribute type and multi-language context.
 */
export interface EnumValue { 
    /**
     * The enumeration ID
     */
    enumId?: string;
    /**
     *  The ID of the attribute type
     */
    attributeTypeId?: string;
    /**
     * This will be represented as a separate attribute value
     */
    enumGroupId?: string;
    /**
     * The multi-language ID that can be used to retrieve the translation in other languages
     */
    multiLanguageId?: string;
    /**
     * The translation of the enumeration ID in human-readable format
     */
    translation?: string;
    /**
     * Indicates whether this object can still be used
     */
    enabled?: boolean;
}

