/**
 * miles-catalog
 * This service may be used to retrieve for    makes, models, catalog vehicles and catalog options. Also generic    options can be retrieved for colors and accessories. Finally, also    vehicle images are available through this service.
 *
 * The version of the OpenAPI document: 2.35.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DynamicAttributeValue } from './dynamic-attribute-value';
import { QualifierDefinition } from './qualifier-definition';
import { MultiLanguageValue } from './multi-language-value';
import { EnumValue } from './enum-value';


/**
 * An accessory generic options contained by this response
 */
export interface FindAccessoryGenericOption { 
    /**
     * The ID of the accessory generic option
     */
    genericOptionId?: string;
    /**
     * The start date from which the accessory generic option is available
     */
    availableFrom?: string;
    /**
     * The end date to which the accessory generic option is available
     */
    availableTo?: string;
    description?: MultiLanguageValue;
    /**
     * If the presence of the accessory generic option must be checked
     */
    checkPresence?: boolean;
    optionType?: EnumValue;
    /**
     * The reference of the accessory generic option
     */
    reference?: string;
    /**
     * The residual value coefficient of the accessory generic option
     */
    residualValueCoefficient?: number;
    /**
     * The residual value percentage of the accessory generic option
     */
    residualValuePercentage?: number;
    qualifier1?: QualifierDefinition;
    qualifier2?: QualifierDefinition;
    qualifier3?: QualifierDefinition;
    /**
     * Indicates whether the description of the accessory generic option is overridable
     */
    descriptionOverridable?: boolean;
    optionCategory?: EnumValue;
    /**
     * A map of dynamic attributes
     */
    dynamicAttributes?: { [key: string]: DynamicAttributeValue; };
}

