/**
 * miles-catalog
 * This service may be used to retrieve for    makes, models, catalog vehicles and catalog options. Also generic    options can be retrieved for colors and accessories. Finally, also    vehicle images are available through this service.
 *
 * The version of the OpenAPI document: 2.35.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SortBy } from './sort-by';
import { VehicleFilter } from './vehicle-filter';


export interface FindCatalogVehiclesRequest { 
    /**
     * The list of vehicle filters
     */
    vehicleFilters?: Array<VehicleFilter>;
    /**
     * The model ID(s) used to filter the catalog vehicles
     */
    modelIds?: Set<string>;
    /**
     * The max number of catalog vehicles you want returned
     */
    count?: number;
    /**
     * The amount of catalog vehicles to skip
     */
    offset?: number;
    sortBy?: SortBy;
    /**
     * The field that defines which fields will be available in response content
     */
    detailLevel?: FindCatalogVehiclesRequest.DetailLevelEnum;
}
export namespace FindCatalogVehiclesRequest {
    export type DetailLevelEnum = 'ID_ONLY' | 'DETAILED';
    export const DetailLevelEnum = {
        IdOnly: 'ID_ONLY' as DetailLevelEnum,
        Detailed: 'DETAILED' as DetailLevelEnum
    };
}


