/**
 * miles-catalog
 * This service may be used to retrieve for    makes, models, catalog vehicles and catalog options. Also generic    options can be retrieved for colors and accessories. Finally, also    vehicle images are available through this service.
 *
 * The version of the OpenAPI document: 2.35.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FindAccessoryGenericOption } from './find-accessory-generic-option';


export interface FindAccessoryGenericOptionsResponse { 
    /**
     * The list of accessory generic options
     */
    genericOptions?: Array<FindAccessoryGenericOption>;
    /**
     * The number of accessory generic options
     */
    totalCount?: number;
}

