/**
 * miles-catalog
 * This service may be used to retrieve for    makes, models, catalog vehicles and catalog options. Also generic    options can be retrieved for colors and accessories. Finally, also    vehicle images are available through this service.
 *
 * The version of the OpenAPI document: 2.35.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TechnicalVehicleSpecification } from './technical-vehicle-specification';


export interface FindTechnicalVehicleSpecificationsResponse { 
    /**
     * A list of technical vehicle specification types
     */
    technicalVehicleSpecifications?: Array<TechnicalVehicleSpecification>;
    /**
     * The number of technical vehicle specifications that qualify for the filters
     */
    totalCount?: number;
}

