/**
 * miles-catalog
 * This service may be used to retrieve for    makes, models, catalog vehicles and catalog options. Also generic    options can be retrieved for colors and accessories. Finally, also    vehicle images are available through this service.
 *
 * The version of the OpenAPI document: 2.35.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DynamicAttributeValue } from './dynamic-attribute-value';
import { MultiLanguageValue } from './multi-language-value';
import { EnumValue } from './enum-value';


/**
 * Option that the car has
 */
export interface FindCatalogVehicleOption { 
    /**
     * The ID of the catalog vehicle option
     */
    catalogOptionId?: string;
    description?: MultiLanguageValue;
    optionType?: EnumValue;
    optionUse?: EnumValue;
    /**
     * Indicates whether the catalog vehicle option is default
     */
    isDefault?: boolean;
    /**
     * A map of dynamic attributes
     */
    dynamicAttributes?: { [key: string]: DynamicAttributeValue; };
}

