/**
 * miles-catalog
 * This service may be used to retrieve for    makes, models, catalog vehicles and catalog options. Also generic    options can be retrieved for colors and accessories. Finally, also    vehicle images are available through this service.
 *
 * The version of the OpenAPI document: 2.35.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DoubleUnitValue } from './double-unit-value';


/**
 * The electrical specification ranges of the model
 */
export interface ModelElectricalVehicleSpecs { 
    /**
     * The upper limit of the battery capacity in kWh of the linked catalog vehicles
     */
    batteryCapacityUpperLimit?: number;
    /**
     * The lower limit of the battery capacity in kWh of the linked catalog vehicles
     */
    batteryCapacityLowerLimit?: number;
    batteryRangeUpperLimit?: DoubleUnitValue;
    batteryRangeLowerLimit?: DoubleUnitValue;
    electricConsumption?: DoubleUnitValue;
}

