/**
 * miles-catalog
 * This service may be used to retrieve for    makes, models, catalog vehicles and catalog options. Also generic    options can be retrieved for colors and accessories. Finally, also    vehicle images are available through this service.
 *
 * The version of the OpenAPI document: 2.35.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Miles API v1 representation of a currency value.
 */
export interface MultiCurrencyValue { 
    /**
     * The value that holds the currency amount
     */
    value?: number;
    /**
     * The currency amount in a different currency
     */
    currencyValue?: number;
    /**
     * The ID of the currency
     */
    currencyId?: string;
}

