/**
 * miles-catalog
 * This service may be used to retrieve for    makes, models, catalog vehicles and catalog options. Also generic    options can be retrieved for colors and accessories. Finally, also    vehicle images are available through this service.
 *
 * The version of the OpenAPI document: 2.35.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Miles API v1 representation of a qualifier definition value.
 */
export interface QualifierDefinition { 
    /**
     * The name of the qualifier definition
     */
    name?: string;
    /**
     * The multi-language ID that can be used to retrieve the translation in other languages
     */
    multiLanguageId?: string;
    /**
     * The qualifier type ID
     */
    qualifierType?: string;
    /**
     * Based on this integer the \'defaultValue\' will consist of a value matching these types:   * 1  = MultiLanguageValue   * 2  = EnumValue   * 3  = MultiCurrencyValue   * 4  = DoubleUnitValue   * 5  = IntegerUnitValue   * 6  = StringValue   * 7  = IntegerValue   * 8  = DoubleValue   * 9  = BooleanValue   * 10 = UnnamedValue   * 11 = DateValue   * 12 = TimeValue   * 13 = DateTimeValue   * 14 = ZonedDateTimeValue   * 15 = LongValue  
     */
    defaultValueType?: number;
    /**
     * An object that contains the actual value
     */
    defaultValue?: object;
    /**
     * An object that contains the actual value
     */
    value?: object;
    translation?: string;
    valueType?: number;
}

