/**
 * miles-catalog
 * This service may be used to retrieve for    makes, models, catalog vehicles and catalog options. Also generic    options can be retrieved for colors and accessories. Finally, also    vehicle images are available through this service.
 *
 * The version of the OpenAPI document: 2.35.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * A vehicle filter
 */
export interface VehicleFilterVehicle { 
    /**
     * The ID of the make
     */
    makeId?: string;
    /**
     * A list of model ID\'s
     */
    modelIds?: Array<string>;
}

