/**
 * miles-catalog
 * This service may be used to retrieve for    makes, models, catalog vehicles and catalog options. Also generic    options can be retrieved for colors and accessories. Finally, also    vehicle images are available through this service.
 *
 * The version of the OpenAPI document: 2.35.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MinMaxValidation } from './min-max-validation';
import { VehicleFilterVehicle } from './vehicle-filter-vehicle';


/**
 * The list of vehicle filters
 */
export interface VehicleFilter { 
    /**
     * A list of body styles
     */
    filterBodyStyleIds?: Array<string>;
    /**
     * A list of vehicle categories
     */
    filterVehicleCategoryIds?: Array<string>;
    /**
     * A list of fuel types
     */
    filterFuelTypeIds?: Array<string>;
    /**
     * A list of fuel type groups
     */
    filterFuelTypeGroupIds?: Array<string>;
    /**
     * A list of vehicle natures
     */
    filterVehicleNatureIds?: Array<string>;
    /**
     * A list of power trains
     */
    filterPowerTrainIds?: Array<string>;
    /**
     * A list of numbers of doors
     */
    filterNumberOfDoorIds?: Array<string>;
    /**
     * A list of transmission groups
     */
    filterTransmissionGroupIds?: Array<string>;
    /**
     * A list of energy labels
     */
    filterEnergyLabelIds?: Array<string>;
    /**
     * A list of vehicle filters
     */
    filterVehicles?: Array<VehicleFilterVehicle>;
    /**
     * A list of wildcard filters for code
     */
    filterCodes?: Array<string>;
    /**
     * The maximum catalog price of the vehicle
     */
    filterMaxCatalogPrice?: number;
    /**
     * The maximum cc of the vehicle
     */
    filterMaxCC?: number;
    /**
     * The date on which the vehicle should be available
     */
    filterAvailableOn?: string;
    /**
     * A list of min-max-validation filters
     */
    minMaxValidations?: Array<MinMaxValidation>;
    /**
     * The filter type
     */
    type?: VehicleFilter.TypeEnum;
}
export namespace VehicleFilter {
    export type TypeEnum = 'included' | 'excluded';
    export const TypeEnum = {
        Included: 'included' as TypeEnum,
        Excluded: 'excluded' as TypeEnum
    };
}


