/**
 * miles-contract
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.124.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MultiLanguageValue } from './multi-language-value';
import { Country } from './country';


/**
 * The address
 */
export interface Address { 
    /**
     * The address ID
     */
    addressId?: string;
    addressLine1?: MultiLanguageValue;
    addressLine1Number?: MultiLanguageValue;
    addressLine2?: MultiLanguageValue;
    addressLine3?: MultiLanguageValue;
    city?: MultiLanguageValue;
    locationIdentification?: MultiLanguageValue;
    /**
     * The postal code of the address
     */
    postalCode?: string;
    state?: MultiLanguageValue;
    /**
     * Indicates whether the address must be deleted, which is only possible when the address ID is given
     */
    deleted?: boolean;
    country?: Country;
}

