/**
 * miles-contract
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.124.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DynamicAttributeValue } from './dynamic-attribute-value';
import { Language } from './language';
import { Customer } from './customer';
import { EnumValue } from './enum-value';
import { PhoneNumber } from './phone-number';
import { DriverAddress } from './driver-address';
import { InternetReference } from './internet-reference';


export interface AllocatedDriverResponse { 
    /**
     * The contact ID of the driver
     */
    driverId?: string;
    /**
     * The first name of the driver
     */
    firstName?: string;
    /**
     * The middle name of the driver
     */
    middleName?: string;
    /**
     * The last name of the driver
     */
    lastName?: string;
    /**
     * The identification of the driver
     */
    identification?: string;
    /**
     * Indicates whether the driver is the main driver on the quote
     */
    isMainDriver?: boolean;
    /**
     * The ID of the customer this driver belongs to
     */
    customerId?: string;
    /**
     * The date of birth of the driver
     */
    dateOfBirth?: string;
    /**
     * The official registration of the driver
     */
    officialRegistration?: string;
    gender?: EnumValue;
    personTitle?: EnumValue;
    driverStatus?: EnumValue;
    driverAddress?: DriverAddress;
    /**
     * A list of phone numbers
     */
    phoneNumbers?: Array<PhoneNumber>;
    /**
     * A list of internet references
     */
    internetReferences?: Array<InternetReference>;
    /**
     * A list of customers
     */
    customers?: Array<Customer>;
    language?: Language;
    /**
     * A map of dynamic attributes
     */
    dynamicAttributes?: { [key: string]: DynamicAttributeValue; };
}

