/**
 * miles-contract
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.124.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DynamicAttributeValue } from './dynamic-attribute-value';
import { MultiCurrencyValue } from './multi-currency-value';
import { DoubleUnitValue } from './double-unit-value';
import { ProductConfiguration } from './product-configuration';


/**
 * The amendment product
 */
export interface AmendmentProduct { 
    /**
     * The ID of the amendment product
     */
    amendmentProductId?: string;
    mileage?: DoubleUnitValue;
    annualMileage?: DoubleUnitValue;
    term?: DoubleUnitValue;
    leasePriceInclFuelExlVat?: MultiCurrencyValue;
    purchaseOptionValue?: MultiCurrencyValue;
    productConfiguration?: ProductConfiguration;
    /**
     * A map of dynamic attributes
     */
    dynamicAttributes?: { [key: string]: DynamicAttributeValue; };
}

