/**
 * miles-contract
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.124.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UnnamedValue } from './unnamed-value';
import { MultiCurrencyValue } from './multi-currency-value';
import { BikeOption } from './bike-option';
import { MultiLanguageValue } from './multi-language-value';
import { EnumValue } from './enum-value';


/**
 * Bike option packs
 */
export interface BikeOptionPack { 
    /**
     * The ID of the bike option
     */
    bikeOptionId?: string;
    catalogPrice?: MultiCurrencyValue;
    catalogVAT?: MultiCurrencyValue;
    catalogPriceInclVAT?: MultiCurrencyValue;
    description?: MultiLanguageValue;
    discountAmount?: MultiCurrencyValue;
    /**
     * The discount percentage
     */
    discountPercentage?: number;
    /**
     * Indicates whether the bike option is standard
     */
    isStandard?: boolean;
    /**
     * Indicates whether the bike option is mandatory
     */
    isMandatory?: boolean;
    /**
     * The option code of the bike option
     */
    optionCode?: string;
    qualifier1?: UnnamedValue;
    qualifier2?: UnnamedValue;
    qualifier3?: UnnamedValue;
    optionType?: EnumValue;
    /**
     * A list of bike option packs
     */
    optionPacks?: Array<BikeOptionPack>;
    /**
     * A list of bike options
     */
    options?: Array<BikeOption>;
}

