/**
 * miles-contract
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.124.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * A broker company
 */
export interface BrokerCompanyReference { 
    /**
     * The ID of the broker company
     */
    brokerCompanyId?: string;
    /**
     * The trading name of the broker company
     */
    tradingName?: string;
}

