/**
 * miles-contract
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.124.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The broker contact on the termination quote
 */
export interface BrokerContact { 
    /**
     * Broker contact ID
     */
    brokerContactId?: string;
    /**
     * Broker contact identification
     */
    brokerContactIdentification?: string;
}

