/**
 * miles-contract
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.124.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The driver of the retail contract
 */
export interface ContractDriver { 
    /**
     * The ID of the contract driver
     */
    driverId?: string;
    /**
     * The first name of the contract driver
     */
    firstName?: string;
    /**
     * The last name of the contract driver
     */
    lastName?: string;
    /**
     * The middle name of the contract driver
     */
    middleName?: string;
    /**
     * The identification of the contract driver
     */
    identification?: string;
}

