/**
 * miles-contract
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.124.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The contract to be terminated with this quote
 */
export interface ContractReference { 
    /**
     * The ID of the contract
     */
    contractId?: string;
    /**
     * The reference of the contract
     */
    reference?: string;
}

