/**
 * miles-contract
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.124.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The customer on the contract
 */
export interface Customer { 
    /**
     * The ID of the customer
     */
    customerId?: string;
    /**
     * Deprecated since 2022-06-01 and version 2.40.0 in favor of legalName
     */
    businessUnitLegalName?: string;
    /**
     * The legal name of the business unit
     */
    legalName?: string;
    /**
     * The trading name of the customer
     */
    tradingName?: string;
}

