/**
 * miles-contract
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.124.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MultiLanguageValue } from './multi-language-value';


/**
 * The document type of the document linked to a contract
 */
export interface DocumentTypeReference { 
    /**
     * The ID of the document type
     */
    documentTypeId?: string;
    description?: MultiLanguageValue;
    name?: MultiLanguageValue;
}

