/**
 * miles-contract
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.124.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Miles API v1 representation of a dynamic attribute value.It has a \'valueType\' as a discriminator for the actual \'value\'.The \'sysRepAttributeId\' identifies which attribute value is represented.
 */
export interface DynamicAttributeValue { 
    /**
     * Based on this integer the \'value\' will consist of a value matching these types:   * 1  = MultiLanguageValue   * 2  = EnumValue   * 3  = MultiCurrencyValue   * 4  = DoubleUnitValue   * 5  = IntegerUnitValue   * 6  = StringValue   * 7  = IntegerValue   * 8  = DoubleValue   * 9  = BooleanValue   * 10 = UnnamedValue   * 11 = DateValue   * 12 = TimeValue   * 13 = DateTimeValue   * 14 = ZonedDateTimeValue   * 15 = LongValue  
     */
    valueType?: number;
    /**
     * An object that contains the actual value
     */
    value?: object;
    /**
     * The Miles back-office application ID that describes the attribute
     */
    sysRepAttributeId?: string;
}

