/**
 * miles-contract
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.124.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FindTireUsage } from './find-tire-usage';


export interface FindTireUsagesResponse { 
    /**
     * List of tire usages
     */
    tireUsages?: Array<FindTireUsage>;
    /**
     * The date and time of the last calculation
     */
    dateTimeOfLastCalculation?: string;
    /**
     * The total number of tire usages
     */
    totalCount?: number;
}

