/**
 * miles-contract
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.124.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DoubleUnitValue } from './double-unit-value';
import { MileageReading } from './mileage-reading';
import { EnumValue } from './enum-value';


export interface FindMileageReadingsResponse { 
    /**
     * The list of mileage readings.
     */
    mileageReadings?: Array<MileageReading>;
    /**
     * Readings total count
     */
    totalCount?: number;
    distanceDeviation?: DoubleUnitValue;
    mileageDeviation?: DoubleUnitValue;
    /**
     * Use mileageDeviationPercentage instead
     */
    distanceDeviationPercentage?: number;
    /**
     * Mileage deviation percentage
     */
    mileageDeviationPercentage?: number;
    annualDistanceDeviation?: DoubleUnitValue;
    annualMileageDeviation?: DoubleUnitValue;
    /**
     * Use annualMileageDeviationPercentage instead
     */
    annualDistanceDeviationPercentage?: number;
    /**
     * Annual mileage deviation percentage
     */
    annualMileageDeviationPercentage?: number;
    totalActualDistance?: DoubleUnitValue;
    totalActualMileage?: DoubleUnitValue;
    totalContractualDistance?: DoubleUnitValue;
    totalContractualMileage?: DoubleUnitValue;
    /**
     * Date and time of the last calculation
     */
    dateTimeOfLastCalculation?: string;
    /**
     * All the applicable enumerations for this list of contracts
     */
    applicableEnumerations?: { [key: string]: Array<EnumValue>; };
}

