/**
 * miles-contract
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.124.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DynamicAttributeValue } from './dynamic-attribute-value';
import { DoubleUnitValue } from './double-unit-value';
import { MultiLanguageValue } from './multi-language-value';
import { Price } from './price';
import { EnumValue } from './enum-value';


/**
 * The product of the quote linked to this contract
 */
export interface FindProduct { 
    /**
     * The ID of the product
     */
    productId?: string;
    productCategory?: EnumValue;
    name?: MultiLanguageValue;
    distance?: DoubleUnitValue;
    duration?: DoubleUnitValue;
    proRataDistance?: DoubleUnitValue;
    mileage?: DoubleUnitValue;
    annualMileage?: DoubleUnitValue;
    term?: DoubleUnitValue;
    applicableLeasePrice?: Price;
    /**
     * A map of other lease prices, the key is the enum ID of the budgetUnit and the value is a price object
     */
    otherLeasePrices?: { [key: string]: Price; };
    purchaseOptionValue?: Price;
    /**
     * A map of dynamic attributes
     */
    dynamicAttributesMap?: { [key: string]: DynamicAttributeValue; };
}

