/**
 * miles-contract
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.124.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EnumValue } from './enum-value';
import { FindRefueling } from './find-refueling';


export interface FindRefuelingsResponse { 
    /**
     * List of refuelings
     */
    refuelings?: Array<FindRefueling>;
    /**
     * The total number of refuelings
     */
    totalCount?: number;
    /**
     * A map of applicable enumerations
     */
    applicableEnumerations?: { [key: string]: Array<EnumValue>; };
}

