/**
 * miles-contract
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.124.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FindTerminationClause } from './find-termination-clause';


export interface FindTerminationClausesResponse { 
    /**
     * A list of termination clauses
     */
    terminationClauses?: Array<FindTerminationClause>;
    /**
     * Number of termination clauses that qualify for the filters
     */
    totalCount?: number;
}

