/**
 * miles-contract
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.124.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FindAmendmentQuote } from './find-amendment-quote';


export interface FindAmendmentQuotesResponse { 
    /**
     * A list of amendment quotes
     */
    amendmentQuotes?: Array<FindAmendmentQuote>;
    /**
     * The total number of amendment quotes for the applied filters
     */
    totalCount?: number;
}

