/**
 * miles-contract
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.124.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The fleet vehicle, deprecated since 2023-01-06 and version 2.87.0 in favor of {@link #contractVehicle}
 */
export interface FleetVehicleId { 
    /**
     * The ID of the fleet vehicle
     */
    fleetVehicleId?: string;
}

