/**
 * miles-contract
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.124.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EnumValue } from './enum-value';


/**
 * Internet reference
 */
export interface InternetReference { 
    /**
     * The ID of the internet reference
     */
    internetReferenceId?: string;
    /**
     * The URL
     */
    url?: string;
    internetReferenceType?: EnumValue;
}

