/**
 * miles-contract
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.124.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MultiLanguageValue } from './multi-language-value';


/**
 * The language for the driver
 */
export interface Language { 
    /**
     * The ID of the language
     */
    languageId?: string;
    /**
     * The reference of the language
     */
    reference?: string;
    translatedDescription?: MultiLanguageValue;
}

