/**
 * miles-contract
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.124.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EnumValue } from './enum-value';


/**
 * The payment preference of the new bank account
 */
export interface PaymentPreference { 
    /**
     * The ID of the payment preference
     */
    paymentPreferenceId?: string;
    /**
     * The reference of the payment preference
     */
    reference?: string;
    /**
     * Indicates if payment is preferred
     */
    isPreferred?: boolean;
    /**
     * The start date from which the payment preference is valid, date included.
     */
    validFrom?: string;
    /**
     * The end date to which the payment preference is valid, date included.
     */
    validTo?: string;
    paymentMethod?: EnumValue;
    preferenceStatus?: EnumValue;
}

