/**
 * miles-contract
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.124.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MultiCurrencyValue } from './multi-currency-value';


/**
 * Payment schedule detail
 */
export interface PaymentScheduleDetail { 
    /**
     * The payment description for this period. In most cases this is a communication that is to be used on the payment for reference
     */
    paymentDescription?: string;
    /**
     * The sequential number of the payment period in time
     */
    periodNumber?: number;
    /**
     * The date on which the payment of this period is or was due
     */
    dueDate?: string;
    amount?: MultiCurrencyValue;
    /**
     * The status of the payment of this period
     */
    status?: string;
}

