/**
 * miles-contract
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.124.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProductSetting } from './product-setting';
import { ProductPricingDetail } from './product-pricing-detail';


/**
 * The configuration of the product
 */
export interface ProductConfiguration { 
    /**
     * The reference of the product configuration
     */
    reference?: string;
    /**
     * The ID of the product
     */
    productId?: string;
    /**
     * The list of product settings found
     */
    productSettings?: Array<ProductSetting>;
    /**
     * The list of product price details found
     */
    priceDetails?: Array<ProductPricingDetail>;
}

