/**
 * miles-contract
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.124.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MultiCurrencyValue } from './multi-currency-value';
import { LeasingCompany } from './leasing-company';
import { Customer } from './customer';
import { EnumValue } from './enum-value';
import { Driver } from './driver';
import { Product } from './product';


/**
 * The request quote
 */
export interface RequestQuote { 
    /**
     * The ID of the quote
     */
    quoteId?: string;
    /**
     * The reference of the quote
     */
    quoteReference?: string;
    /**
     * The description of the quote
     */
    description?: string;
    /**
     * The date when the quote was created
     */
    creationDate?: string;
    /**
     * The date when the quote expires
     */
    expirationDate?: string;
    /**
     * Deprecated since \'2.58.0\' in favor of \'terminationDate\'
     */
    changeDate?: string;
    /**
     * The date when the quote was terminated
     */
    terminationDate?: string;
    /**
     * Indicates if the quote is approved
     */
    isApproved?: boolean;
    /**
     * The driver name specified in the request
     */
    requestDriverName?: string;
    /**
     * The external reference of the request
     */
    requestExternalReference?: string;
    /**
     * The user account specified in the request
     */
    requestUserAccount?: string;
    terminationCost?: MultiCurrencyValue;
    terminationCostInclVat?: MultiCurrencyValue;
    quoteReason?: EnumValue;
    quoteStatus?: EnumValue;
    quoteType?: EnumValue;
    changeReason?: EnumValue;
    requestType?: EnumValue;
    vehicleCategory?: EnumValue;
    vehicleNature?: EnumValue;
    customer?: Customer;
    driver?: Driver;
    leasingCompany?: LeasingCompany;
    product?: Product;
}

