/**
 * miles-contract
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.124.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DynamicAttributeValue } from './dynamic-attribute-value';
import { MultiCurrencyValue } from './multi-currency-value';
import { DoubleUnitValue } from './double-unit-value';
import { MultiLanguageValue } from './multi-language-value';
import { EnumValue } from './enum-value';
import { RetailProduct } from './retail-product';
import { RetailProductConfiguration } from './retail-product-configuration';


/**
 * The representation of the retail contract product of the retail contract
 */
export interface RetailContractProduct { 
    /**
     * The ID of the retail contract product
     */
    productId?: string;
    /**
     * Deprecated since 2024-01-25 and version 2.118.0 as it was identical to `annualPercentageRate`
     */
    interestRate?: number;
    /**
     * The annual percentage rate (APR), representing the total yearly cost of borrowing, including interest and fees, expressed as a percentage of the loan amount
     */
    annualPercentageRate?: number;
    /**
     * The payment due day, specifying the specific day of the month by which a payment is expected
     */
    paymentDueDay?: number;
    term?: DoubleUnitValue;
    description?: MultiLanguageValue;
    mileage?: DoubleUnitValue;
    annualMileage?: DoubleUnitValue;
    balloonPayment?: MultiCurrencyValue;
    netLoanAmount?: MultiCurrencyValue;
    downPayment?: MultiCurrencyValue;
    tradeInAmount?: MultiCurrencyValue;
    repaymentCurrentCredit?: MultiCurrencyValue;
    productCategory?: EnumValue;
    productConfiguration?: RetailProductConfiguration;
    product?: RetailProduct;
    /**
     * Deprecated since 2024-01-25 and version 2.118.0 in favor of `dynamicAttributes`
     */
    dynamicAttributesMap?: { [key: string]: DynamicAttributeValue; };
    /**
     * A map of dynamic attributes
     */
    dynamicAttributes?: { [key: string]: DynamicAttributeValue; };
}

