/**
 * miles-contract
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.124.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RetailContractBike } from './retail-contract-bike';
import { RetailContractVehicleMake } from './retail-contract-vehicle-make';
import { MultiLanguageValue } from './multi-language-value';
import { RetailContractVehicleModel } from './retail-contract-vehicle-model';
import { RetailContractCar } from './retail-contract-car';


/**
 * The vehicle of the retail contract
 */
export interface RetailContractVehicle { 
    description?: MultiLanguageValue;
    /**
     * The first registration date
     */
    firstRegistrationDate?: string;
    /**
     * The license plate of the vehicle
     */
    licensePlate?: string;
    make?: RetailContractVehicleMake;
    model?: RetailContractVehicleModel;
    /**
     * The type name of the vehicle
     */
    typeName?: string;
    car?: RetailContractCar;
    bike?: RetailContractBike;
}

