/**
 * miles-contract
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.124.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DoubleUnitValue } from './double-unit-value';
import { MultiLanguageValue } from './multi-language-value';
import { EnumValue } from './enum-value';
import { CarOption } from './car-option';
import { Tire } from './tire';


/**
 * Deprecated since 2024-01-25 and version 2.118.0 in favor of `vehicle`
 */
export interface RetailCar { 
    /**
     * ID of the car
     */
    carId?: string;
    description?: MultiLanguageValue;
    /**
     * The VIN of the car
     */
    vin?: string;
    /**
     * First registration date
     */
    firstRegistrationDate?: string;
    /**
     * License plate of the car
     */
    licensePlate?: string;
    /**
     * Acceleration of the car
     */
    acceleration?: number;
    /**
     * CO2 emission value
     */
    co2Emission?: number;
    consumption?: DoubleUnitValue;
    maxWeight?: DoubleUnitValue;
    netWeight?: DoubleUnitValue;
    /**
     * dinHP
     */
    dinHP?: number;
    tire?: Tire;
    makeName?: MultiLanguageValue;
    modelName?: MultiLanguageValue;
    /**
     * Model year of the car
     */
    modelYear?: string;
    /**
     * Type name
     */
    typeName?: string;
    /**
     * Number of passengers
     */
    seatingCapacity?: number;
    transmission?: EnumValue;
    /**
     * kW
     */
    kW?: number;
    /**
     * Fiscal power
     */
    fiscalPower?: number;
    /**
     * List of car options
     */
    carOptions?: Array<CarOption>;
}

