/**
 * miles-contract
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.124.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DoubleUnitValue } from './double-unit-value';
import { EnumValue } from './enum-value';
import { CarOption } from './car-option';
import { Tire } from './tire';


/**
 * The car of the retail contract, it can only return a car or a bike not both
 */
export interface RetailContractCar { 
    /**
     * ID of the car
     */
    carId?: string;
    /**
     * The VIN of the car
     */
    vin?: string;
    /**
     * Acceleration of the car
     */
    acceleration?: number;
    /**
     * CO2 emission value
     */
    co2Emission?: number;
    consumption?: DoubleUnitValue;
    maxWeight?: DoubleUnitValue;
    netWeight?: DoubleUnitValue;
    /**
     * Horse power in DIN
     */
    dinHP?: number;
    tire?: Tire;
    /**
     * Number of passengers
     */
    seatingCapacity?: number;
    transmission?: EnumValue;
    /**
     * kW
     */
    kW?: number;
    /**
     * Fiscal power
     */
    fiscalPower?: number;
    /**
     * The date on which the last known distance was reported
     */
    lastKnownDistanceDate?: string;
    lastKnownDistance?: DoubleUnitValue;
    bodyStyle?: EnumValue;
    /**
     * The path to the image of the car
     */
    imagesPath?: string;
    /**
     * List of car options
     */
    carOptions?: Array<CarOption>;
}

