/**
 * miles-contract
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.124.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { QualifierSetting } from './qualifier-setting';
import { ServiceChoice } from './service-choice';


/**
 * Service
 */
export interface Service { 
    /**
     * Reference of the product service
     */
    reference?: string;
    /**
     * A list of service choices
     */
    choices?: Array<ServiceChoice>;
    /**
     * A list of qualifier settings
     */
    qualifierSettings?: Array<QualifierSetting>;
}

