/**
 * miles-contract
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.124.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SimpleEnumValue } from './simple-enum-value';


/**
 * A signatory
 */
export interface Signatory { 
    /**
     * The ID of the contact
     */
    contactId?: string;
    /**
     * The first name of the signatory
     */
    firstName?: string;
    /**
     * The last name of the signatory
     */
    lastName?: string;
    /**
     * The identification of the signatory
     */
    identification?: string;
    title?: SimpleEnumValue;
    signatoryType?: SimpleEnumValue;
}

