/**
 * miles-contract
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.124.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EnumValue } from './enum-value';


/**
 * The site of the contract quote of the contract
 */
export interface Site { 
    /**
     * The ID of the Site
     */
    siteId?: string;
    /**
     * The name of Site
     */
    name?: string;
    siteType?: EnumValue;
}

