/**
 * miles-contract
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.124.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MultiCurrencyValue } from './multi-currency-value';
import { DoubleUnitValue } from './double-unit-value';
import { MultiLanguageValue } from './multi-language-value';
import { EnumValue } from './enum-value';
import { QualifierValue } from './qualifier-value';


/**
 * Vehicle configuration
 */
export interface VehicleConfiguration { 
    /**
     * The ID of the vehicle configuration
     */
    vehicleConfigurationId?: string;
    /**
     * The ID of the catalog option type
     */
    catalogOptionTypeId?: string;
    /**
     * The ID of the generic option
     */
    genericOptionId?: string;
    /**
     * Option code
     */
    optionCode?: string;
    /**
     * The ID of the supplier
     */
    supplierId?: string;
    /**
     * Additional discount percentage
     */
    additionalDiscountPercentage?: number;
    /**
     * Discount percentage
     */
    discountPercentage?: number;
    /**
     * Residual value coefficient
     */
    residualValueCoefficient?: number;
    /**
     * Residual value percentage
     */
    residualValuePercentage?: number;
    /**
     * Indicates whether the vehicle has the standard configuration
     */
    isStandard?: boolean;
    /**
     * Configuration date
     */
    configurationDate?: string;
    catalogVatCode?: EnumValue;
    deliveryVatCode?: EnumValue;
    optionType?: EnumValue;
    netWeight?: DoubleUnitValue;
    additionalDiscount?: MultiCurrencyValue;
    catalogPrice?: MultiCurrencyValue;
    catalogVat?: MultiCurrencyValue;
    customerPaid?: MultiCurrencyValue;
    defAddDiscountAmount?: MultiCurrencyValue;
    defDiscountAmount?: MultiCurrencyValue;
    deliveryCost?: MultiCurrencyValue;
    deliveryVat?: MultiCurrencyValue;
    discountAmount?: MultiCurrencyValue;
    maintenanceCost?: MultiCurrencyValue;
    residualValue?: MultiCurrencyValue;
    tax?: MultiCurrencyValue;
    description?: MultiLanguageValue;
    qualifier1?: QualifierValue;
    qualifier2?: QualifierValue;
    qualifier3?: QualifierValue;
}

