/**
 * miles-contract
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.124.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MultiLanguageValue } from './multi-language-value';


export interface WarningsInfoDTO { 
    type?: string;
    title?: string;
    detail?: string;
    messages?: Array<MultiLanguageValue>;
    arguments?: Array<string>;
    isInteractiveWarning?: boolean;
    interactiveWarning?: boolean;
}

