/**
 * miles-credit-retail
 * This functional service supports the creation and follow-up of **credit applications**.    For more information, check the **Read Me** tab.
 *
 * The version of the OpenAPI document: 1.29.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The broker contact on the sales quote or the amendment quote linked to the credit application
 */
export interface BrokerContactReference { 
    /**
     * The ID of the broker contact
     */
    brokerContactId?: string;
    /**
     * The identification of the broker contact
     */
    identification?: string;
}

