/**
 * miles-credit-retail
 * This functional service supports the creation and follow-up of **credit applications**.    For more information, check the **Read Me** tab.
 *
 * The version of the OpenAPI document: 1.29.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ContactAddress } from './contact-address';
import { DynamicAttributeValue } from './dynamic-attribute-value';
import { EnumValue } from './enum-value';
import { PhoneNumber } from './phone-number';
import { IndividualPerson } from './individual-person';
import { InternetReference } from './internet-reference';


/**
 * The customer linked to the applicant credit score
 */
export interface Customer { 
    /**
     * The ID of the customer
     */
    customerId?: string;
    /**
     * The trading name
     */
    tradingName?: string;
    /**
     * The legal name of the customer
     */
    legalName?: string;
    /**
     * The official registration of the customer
     */
    officialRegistration?: string;
    /**
     * The VAT number of the customer
     */
    vatNumber?: string;
    /**
     * Establishment date
     */
    establishmentDate?: string;
    /**
     * Additional customer reference. Typically used for mapping to other systems.
     */
    reference?: string;
    legalEntity?: EnumValue;
    taxLiability?: EnumValue;
    customerState?: EnumValue;
    individualPerson?: IndividualPerson;
    /**
     * A list of phone numbers
     */
    phoneNumbers?: Array<PhoneNumber>;
    /**
     * A list of customer contact addresses
     */
    addresses?: Array<ContactAddress>;
    /**
     * A list of internet references
     */
    internetReferences?: Array<InternetReference>;
    /**
     * A map of dynamic attributes
     */
    dynamicAttributes?: { [key: string]: DynamicAttributeValue; };
}

