/**
 * miles-credit-retail
 * This functional service supports the creation and follow-up of **credit applications**.    For more information, check the **Read Me** tab.
 *
 * The version of the OpenAPI document: 1.29.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * An existing customer to be added or removed as applicant. Note that either this parameter or `newApplicant` needs to be set. For users with the role `retail_customer`, the parameter `existingApplicant` can only be used to delete existing applicants and only `newApplicant` can be used to add an applicant.
 */
export interface ExistingApplicant { 
    /**
     * The ID of the customer to add as applicant
     */
    customerId: string;
}

