/**
 * miles-credit-retail
 * This functional service supports the creation and follow-up of **credit applications**.    For more information, check the **Read Me** tab.
 *
 * The version of the OpenAPI document: 1.29.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DynamicAttributeValue } from './dynamic-attribute-value';
import { MultiCurrencyValue } from './multi-currency-value';
import { EnumValue } from './enum-value';


/**
 * The financial information of the customer linked to the applicant credit score
 */
export interface FinancialInfo { 
    grossIncome?: MultiCurrencyValue;
    netIncome?: MultiCurrencyValue;
    otherIncome?: MultiCurrencyValue;
    loanInstallment?: MultiCurrencyValue;
    otherInstallment?: MultiCurrencyValue;
    alimony?: MultiCurrencyValue;
    maritalStatus?: EnumValue;
    children?: EnumValue;
    housingTenure?: EnumValue;
    profession?: EnumValue;
    residencyStatus?: EnumValue;
    /**
     * The dynamic attributes of the financial info object
     */
    dynamicAttributes?: { [key: string]: DynamicAttributeValue; };
}

