/**
 * miles-credit-retail
 * This functional service supports the creation and follow-up of **credit applications**.    For more information, check the **Read Me** tab.
 *
 * The version of the OpenAPI document: 1.29.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MultiLanguageValue } from './multi-language-value';
import { EnumValue } from './enum-value';


/**
 * A document attached to the stipulation
 */
export interface FindStipulationDocument { 
    /**
     * The ID of the stipulation
     */
    stipulationId?: string;
    /**
     * The ID of the document
     */
    documentId?: string;
    /**
     * The type of the document
     */
    fileType?: string;
    /**
     * The creation date of the document
     */
    creationDate?: string;
    name?: MultiLanguageValue;
    description?: MultiLanguageValue;
    documentStatus?: EnumValue;
}

