/**
 * miles-credit-retail
 * This functional service supports the creation and follow-up of **credit applications**.    For more information, check the **Read Me** tab.
 *
 * The version of the OpenAPI document: 1.29.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DynamicAttributeValue } from './dynamic-attribute-value';
import { MultiCurrencyValue } from './multi-currency-value';
import { EnumValue } from './enum-value';


/**
 * Loan information of the customer linked to the applicant credit score
 */
export interface LoanInfo { 
    /**
     * The ID of the loan info. Disclaimer: updating fields on this object will cause the ID to change.
     */
    loanInfoId?: string;
    loanType?: EnumValue;
    /**
     * The number of the contract linked to the loan
     */
    contractNumber?: string;
    principal?: MultiCurrencyValue;
    outstandingAmount?: MultiCurrencyValue;
    monthlyInstallment?: MultiCurrencyValue;
    /**
     * The dynamic attributes of the loan info object
     */
    dynamicAttributes?: { [key: string]: DynamicAttributeValue; };
}

