/**
 * miles-credit-retail
 * This functional service supports the creation and follow-up of **credit applications**.    For more information, check the **Read Me** tab.
 *
 * The version of the OpenAPI document: 1.29.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Miles API v1 representation of a currency value.
 */
export interface MultiCurrencyValue { 
    /**
     * The value that holds the currency amount
     */
    value?: number;
    /**
     * The currency amount in a different currency
     */
    currencyValue?: number;
    /**
     * The ID of the currency
     */
    currencyId?: string;
}

