/**
 * miles-credit-retail
 * This functional service supports the creation and follow-up of **credit applications**.    For more information, check the **Read Me** tab.
 *
 * The version of the OpenAPI document: 1.29.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Operator } from './operator';
import { ValidationElementType } from './validation-element-type';
import { EvaluatorContext } from './evaluator-context';


/**
 * A single condition element
 */
export interface OperatorContext { 
    operator?: Operator;
    value?: EvaluatorContext;
    /**
     * Defines which type an abstract Value, dynamic attribute or qualifier should have: * 1 / MULTI_LANGUAGE = MultiLanguageValue * 2 / ENUM = EnumValue * 3 / MULTI_CURRENCY = MultiCurrencyValue * 4 / DOUBLE_UNIT = DoubleUnitValue * 5 / INTEGER_UNIT = IntegerUnitValue * 6 / STRING = StringValue * 7 / INTEGER = IntegerValue * 8 / DOUBLE = DoubleValue * 9 / BOOLEAN = BooleanValue * 11 / DATE = DateValue * 12 / TIME = TimeValue * 13 / DATE_TIME = DateTimeValue * 14 / ZONED_DATE_TIME = ZonedDateTimeValue * 15 / LONG = LongValue  Both the names and the numbers are allowed
     */
    dynamicType?: OperatorContext.DynamicTypeEnum;
    /**
     * The in-order list of types corresponding to the elements of the condition path. Example:  The condition path \'object.subobject.field\' consists of 3 elements (in-order): \'object\', \'subobject\' and \'field\'. This means that this list will also have 3 elements where the first element will be the type of \'object\', the second element the type of \'subobject\' and the last element the type of \'field\'.
     */
    type?: Array<ValidationElementType>;
}
export namespace OperatorContext {
    export type DynamicTypeEnum = '1' | 'MULTI_LANGUAGE' | '2' | 'ENUM' | '3' | 'MULTI_CURRENCY' | '4' | 'DOUBLE_UNIT' | '5' | 'INTEGER_UNIT' | '6' | 'STRING' | '7' | 'INTEGER' | '8' | 'DOUBLE' | '9' | 'BOOLEAN' | '11' | 'DATE' | '12' | 'TIME' | '13' | 'DATE_TIME' | '14' | 'ZONED_DATE_TIME' | '15' | 'LONG';
    export const DynamicTypeEnum = {
        _1: '1' as DynamicTypeEnum,
        MultiLanguage: 'MULTI_LANGUAGE' as DynamicTypeEnum,
        _2: '2' as DynamicTypeEnum,
        Enum: 'ENUM' as DynamicTypeEnum,
        _3: '3' as DynamicTypeEnum,
        MultiCurrency: 'MULTI_CURRENCY' as DynamicTypeEnum,
        _4: '4' as DynamicTypeEnum,
        DoubleUnit: 'DOUBLE_UNIT' as DynamicTypeEnum,
        _5: '5' as DynamicTypeEnum,
        IntegerUnit: 'INTEGER_UNIT' as DynamicTypeEnum,
        _6: '6' as DynamicTypeEnum,
        String: 'STRING' as DynamicTypeEnum,
        _7: '7' as DynamicTypeEnum,
        Integer: 'INTEGER' as DynamicTypeEnum,
        _8: '8' as DynamicTypeEnum,
        Double: 'DOUBLE' as DynamicTypeEnum,
        _9: '9' as DynamicTypeEnum,
        Boolean: 'BOOLEAN' as DynamicTypeEnum,
        _11: '11' as DynamicTypeEnum,
        Date: 'DATE' as DynamicTypeEnum,
        _12: '12' as DynamicTypeEnum,
        Time: 'TIME' as DynamicTypeEnum,
        _13: '13' as DynamicTypeEnum,
        DateTime: 'DATE_TIME' as DynamicTypeEnum,
        _14: '14' as DynamicTypeEnum,
        ZonedDateTime: 'ZONED_DATE_TIME' as DynamicTypeEnum,
        _15: '15' as DynamicTypeEnum,
        Long: 'LONG' as DynamicTypeEnum
    };
}


