/**
 * miles-credit-retail
 * This functional service supports the creation and follow-up of **credit applications**.    For more information, check the **Read Me** tab.
 *
 * The version of the OpenAPI document: 1.29.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DynamicAttributeValue } from './dynamic-attribute-value';
import { SalesQuoteReference } from './sales-quote-reference';
import { EnumValue } from './enum-value';
import { ApplicantCreditScoreReference } from './applicant-credit-score-reference';
import { AmendmentQuoteReference } from './amendment-quote-reference';


export interface SubmitCreditApplication { 
    /**
     * The ID of the credit application
     */
    creditApplicationId?: string;
    amendmentQuote?: AmendmentQuoteReference;
    salesQuote?: SalesQuoteReference;
    status?: EnumValue;
    /**
     * The reference of the credit application
     */
    reference?: string;
    /**
     * The list of applicant credit scores linked to the credit application
     */
    applicantCreditScores?: Array<ApplicantCreditScoreReference>;
    /**
     * The dynamic attributes of the credit application
     */
    dynamicAttributes?: { [key: string]: DynamicAttributeValue; };
}

