/**
 * miles-credit-retail
 * This functional service supports the creation and follow-up of **credit applications**.    For more information, check the **Read Me** tab.
 *
 * The version of the OpenAPI document: 1.29.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UpdateCustomerInfo } from './update-customer-info';
import { UpdateLoanInfo } from './update-loan-info';
import { SimpleDynamicAttributeValue } from './simple-dynamic-attribute-value';
import { UpdateEmploymentInfo } from './update-employment-info';
import { UpdateFinancialInfo } from './update-financial-info';


export interface UpdateApplicantCreditScoreRequest { 
    customerInfo?: UpdateCustomerInfo;
    /**
     * The list of employment information of the customer linked to the applicant credit score that needs to be added, updated or removed
     */
    employmentInfos?: Array<UpdateEmploymentInfo>;
    financialInfo?: UpdateFinancialInfo;
    /**
     * The list of loan information of the customer linked to the applicant credit score that needs to be added, updated or removed
     */
    loanInfos?: Array<UpdateLoanInfo>;
    /**
     * The dynamic attributes of the applicant credit score to update
     */
    dynamicAttributes?: { [key: string]: SimpleDynamicAttributeValue; };
}

