/**
 * miles-credit-retail
 * This functional service supports the creation and follow-up of **credit applications**.    For more information, check the **Read Me** tab.
 *
 * The version of the OpenAPI document: 1.29.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UpdateEmploymentHistory } from './update-employment-history';
import { SimpleEnumValue } from './simple-enum-value';
import { SimpleDynamicAttributeValue } from './simple-dynamic-attribute-value';


/**
 * Individual person of the customer
 */
export interface UpdateIndividualPerson { 
    /**
     * First name
     */
    firstName?: string;
    /**
     * Middle name
     */
    middleName?: string;
    /**
     * Last name
     */
    lastName?: string;
    /**
     * Second last name
     */
    secondLastName?: string;
    /**
     * Maiden name
     */
    maidenName?: string;
    /**
     * Initials
     */
    initials?: string;
    /**
     * Birth date
     */
    birthDate?: string;
    gender?: SimpleEnumValue;
    personTitle?: SimpleEnumValue;
    /**
     * The nationality
     */
    nationality?: string;
    /**
     * The mother tongue
     */
    language?: string;
    /**
     * The country ISO code of the birth place
     */
    countryOfBirth?: string;
    residencyStatus?: SimpleEnumValue;
    /**
     * The number of people dependent on the person
     */
    numberOfDependents?: number;
    /**
     * Official registration
     */
    officialRegistration?: string;
    /**
     * A person\'s place of birth
     */
    placeOfBirth?: string;
    maritalStatus?: SimpleEnumValue;
    housingTenure?: SimpleEnumValue;
    employmentHistory?: UpdateEmploymentHistory;
    /**
     * A map of dynamic attributes
     */
    dynamicAttributes?: { [key: string]: SimpleDynamicAttributeValue; };
}

