/**
 * miles-credit-retail
 * This functional service supports the creation and follow-up of **credit applications**.    For more information, check the **Read Me** tab.
 *
 * The version of the OpenAPI document: 1.29.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MultiCurrencyValue } from './multi-currency-value';
import { SimpleEnumValue } from './simple-enum-value';
import { SimpleDynamicAttributeValue } from './simple-dynamic-attribute-value';


/**
 * The financial information about the customer linked to applicant credit score that needs to be updated
 */
export interface UpdateFinancialInfo { 
    grossIncome?: MultiCurrencyValue;
    netIncome?: MultiCurrencyValue;
    otherIncome?: MultiCurrencyValue;
    loanInstallment?: MultiCurrencyValue;
    otherInstallment?: MultiCurrencyValue;
    alimony?: MultiCurrencyValue;
    maritalStatus?: SimpleEnumValue;
    children?: SimpleEnumValue;
    housingTenure?: SimpleEnumValue;
    profession?: SimpleEnumValue;
    residencyStatus?: SimpleEnumValue;
    /**
     * The dynamic attributes of the financial info object that need to be added, updated or removed
     */
    dynamicAttributes?: { [key: string]: SimpleDynamicAttributeValue; };
}

