/**
 * miles-credit-retail
 * This functional service supports the creation and follow-up of **credit applications**.    For more information, check the **Read Me** tab.
 *
 * The version of the OpenAPI document: 1.29.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The type of an element in the condition path
 */
export interface ValidationElementType { 
    /**
     * Defines the type corresponding with the element  Possible types: - An object name, for objects with a fixed set of fields - Map (objects with dynamic keys) - Enum (enumerations) - String (text) - Integer - Number (decimal numbers) - Boolean - Time - Date - DateTime - ZonedDateTime
     */
    value?: string;
    /**
     * Defines if the element contains multiple values (`true`) or only a single value (`false`)
     */
    isArray?: boolean;
    /**
     * When the element contains a propety list selector, this fields will contain the type of the property.  Possible types: - An object name, for objects with a fixed set of fields - Map (objects with dynamic keys) - Enum (enumerations) - String (text) - Integer - Number (decimal numbers) - Boolean - Time - Date - DateTime - ZonedDateTime
     */
    property?: string;
}

