/**
 * miles-credit-retail
 * This functional service supports the creation and follow-up of **credit applications**.    For more information, check the **Read Me** tab.
 *
 * The version of the OpenAPI document: 1.29.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DefaultValue } from './default-value';
import { ValidationElementType } from './validation-element-type';
import { ConditionalValidation } from './conditional-validation';
import { Mandatory } from './mandatory';


/**
 * A path element to the element to evaluate
 */
export interface ValidationPath { 
  [key: string]: ValidationPath | any;


    _mandatory?: Mandatory;
    /**
     * The condition to use for the conditionally required check
     */
    _condition?: string;
    /**
     * The validation condition to which this field should apply
     */
    _validation?: string;
    _default?: DefaultValue;
    _type?: ValidationElementType;
    /**
     * The custom error message in case the property is not provided. The property names will be an ISO 639-2 language code.
     */
    _mandatoryErrorMessage?: { [key: string]: string; };
    /**
     * The custom error message in case the property validation is not correct. The property names will be an ISO 639-2 language code.
     */
    _validationErrorMessage?: { [key: string]: string; };
    /**
     * The list of conditional validation rules
     */
    _conditionalValidation?: Array<ConditionalValidation>;
}
export namespace ValidationPath {
}


